/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AngsuranDAO;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author feryo
 */
public class Angsuran extends javax.swing.JPanel {
    private final AngsuranDAO angsuranDAO = new AngsuranDAO();
    private final List<String> pilihanPinjaman = new ArrayList<>();
    private final Map<String, Integer> idPinjamanByPilihan = new HashMap<>();
    private final Map<String, String> namaAnggotaByPilihan = new HashMap<>();
    private boolean sedangFilterPinjaman = false;

    /**
     * Creates new form Angsuran
     */
    public Angsuran() {
        initComponents();
        tnamaang.setEditable(false);
        cbbnopinjaman.setEditable(true);
        muatComboPinjaman();
        aktifkanSearchComboPinjaman();
        btnresetang.addActionListener(e -> resetFormAngsuran());
        resetFormAngsuran();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbnopinjaman = new javax.swing.JComboBox<>();
        tnamaang = new javax.swing.JTextField();
        tang = new javax.swing.JTextField();
        tjmlang = new javax.swing.JTextField();
        tketang = new javax.swing.JTextField();
        btnsimpanang = new javax.swing.JButton();
        btnresetang = new javax.swing.JButton();
        tglangs = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelangsuran = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblsisasimpanan = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 331));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("INPUT ANGSURAN");

        jLabel2.setText("No. Pinjaman ");

        jLabel3.setText("Nama ");

        jLabel4.setText("Jumlah Bayar");

        jLabel5.setText("Angsuran ke ");

        jLabel6.setText("Tanggal Bayar ");

        jLabel7.setText("Keterangan");

        cbbnopinjaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tnamaang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaangActionPerformed(evt);
            }
        });

        tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangActionPerformed(evt);
            }
        });

        tjmlang.setText("Rp .");

        tketang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tketangActionPerformed(evt);
            }
        });

        btnsimpanang.setBackground(new java.awt.Color(0, 51, 204));
        btnsimpanang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsimpanang.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpanang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/diskette.png"))); // NOI18N
        btnsimpanang.setText("Simpan");
        btnsimpanang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanangActionPerformed(evt);
            }
        });

        btnresetang.setBackground(new java.awt.Color(153, 0, 0));
        btnresetang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnresetang.setForeground(new java.awt.Color(255, 255, 255));
        btnresetang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/undowhite.png"))); // NOI18N
        btnresetang.setText("Reset");

        tglangs.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnsimpanang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnresetang, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglangs, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tjmlang)
                                        .addComponent(cbbnopinjaman, 0, 125, Short.MAX_VALUE)
                                        .addComponent(tnamaang)
                                        .addComponent(tang)
                                        .addComponent(tketang)))))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbnopinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnamaang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglangs, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tjmlang))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tketang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpanang)
                    .addComponent(btnresetang))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("RIWAYAT ANGSURAN");

        tabelangsuran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabelangsuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Angsuran Ke", "Tgl Jatuh Tempo", "Jumlah ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelangsuran);
        if (tabelangsuran.getColumnModel().getColumnCount() > 0) {
            tabelangsuran.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Sisa Simpanan :");

        lblsisasimpanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsisasimpanan.setText("Rp. 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsisasimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(lblsisasimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tnamaangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaangActionPerformed

    private void tketangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tketangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tketangActionPerformed

    private void btnsimpanangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanangActionPerformed
        simpanDataAngsuran();
    }//GEN-LAST:event_btnsimpanangActionPerformed

    private void tangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tangActionPerformed

    private void simpanDataAngsuran() {
        Integer idPinjaman = getIdPinjamanTerpilih();
        int angsuranKe = parseInteger(tang.getText());
        BigDecimal jumlahBayar = parseNominal(tjmlang.getText());
        Date tanggalBayar = tglangs.getDate();

        if (idPinjaman == null) {
            JOptionPane.showMessageDialog(this, "Pilih No. Pinjaman terlebih dahulu.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (angsuranKe <= 0) {
            JOptionPane.showMessageDialog(this, "Angsuran ke harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tanggalBayar == null) {
            JOptionPane.showMessageDialog(this, "Tanggal bayar wajib diisi.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jumlahBayar.compareTo(BigDecimal.ZERO) <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah bayar harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            AngsuranDAO.PinjamanInfo pinjaman = angsuranDAO.getPinjamanInfo(idPinjaman);
            BigDecimal sisaSebelumBayar = pinjaman.sisaPinjaman();

            if (sisaSebelumBayar.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "Pinjaman ini sudah lunas.", "Validasi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (jumlahBayar.compareTo(sisaSebelumBayar) > 0) {
                int pilihan = JOptionPane.showConfirmDialog(
                        this,
                        "Jumlah bayar melebihi sisa pinjaman.\nSisa pinjaman: " + formatRupiah(sisaSebelumBayar) + "\nTetap simpan?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (pilihan != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            angsuranDAO.insertAngsuran(idPinjaman, angsuranKe, tanggalBayar, jumlahBayar, tketang.getText().trim());
            JOptionPane.showMessageDialog(this, "Data angsuran berhasil disimpan.");
            muatComboPinjaman();
            resetFormAngsuran();
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menyimpan data angsuran.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void muatComboPinjaman() {
        pilihanPinjaman.clear();
        idPinjamanByPilihan.clear();
        namaAnggotaByPilihan.clear();

        try {
            for (AngsuranDAO.PinjamanPilihan pinjaman : angsuranDAO.getPinjamanAktif()) {
                String pilihan = pinjaman.pilihan();

                pilihanPinjaman.add(pilihan);
                idPinjamanByPilihan.put(pilihan, pinjaman.idPinjaman());
                namaAnggotaByPilihan.put(pilihan, pinjaman.nama());
            }

            isiModelComboPinjaman(pilihanPinjaman, "");
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data pinjaman.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void aktifkanSearchComboPinjaman() {
        JTextField editor = (JTextField) cbbnopinjaman.getEditor().getEditorComponent();

        cbbnopinjaman.addActionListener(e -> tampilkanPinjamanTerpilih());
        editor.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterPinjaman();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterPinjaman();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterPinjaman();
            }

            private void filterPinjaman() {
                if (sedangFilterPinjaman) {
                    return;
                }

                SwingUtilities.invokeLater(() -> {
                    String keyword = editor.getText();
                    List<String> hasil = new ArrayList<>();

                    for (String pilihan : pilihanPinjaman) {
                        if (pilihan.toLowerCase().contains(keyword.toLowerCase())) {
                            hasil.add(pilihan);
                        }
                    }

                    isiModelComboPinjaman(hasil, keyword);
                    if (!keyword.isBlank()) {
                        cbbnopinjaman.showPopup();
                    }
                });
            }
        });
    }

    private void isiModelComboPinjaman(List<String> data, String teksEditor) {
        sedangFilterPinjaman = true;

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        cbbnopinjaman.setModel(model);
        cbbnopinjaman.setSelectedItem(teksEditor);

        sedangFilterPinjaman = false;
    }

    private void tampilkanPinjamanTerpilih() {
        Integer idPinjaman = getIdPinjamanTerpilih();
        Object selectedItem = cbbnopinjaman.getSelectedItem();

        if (idPinjaman == null || selectedItem == null) {
            tnamaang.setText("");
            lblsisasimpanan.setText("0");
            kosongkanTabelAngsuran();
            return;
        }

        String pilihan = selectedItem.toString();
        tnamaang.setText(namaAnggotaByPilihan.getOrDefault(pilihan, ""));

        try {
            AngsuranDAO.PinjamanInfo info = angsuranDAO.getPinjamanInfo(idPinjaman);
            BigDecimal sisa = info.sisaPinjaman();
            lblsisasimpanan.setText(formatRupiah(sisa));
            tang.setText(String.valueOf(angsuranDAO.getAngsuranBerikutnya(idPinjaman)));
            tjmlang.setText(formatAngkaPlain(info.angsuranPerBulan()));
            loadRiwayatAngsuran(idPinjaman);
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat detail pinjaman.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private Integer getIdPinjamanTerpilih() {
        Object selectedItem = cbbnopinjaman.getSelectedItem();
        if (selectedItem == null) {
            return null;
        }

        return idPinjamanByPilihan.get(selectedItem.toString());
    }

    private void loadRiwayatAngsuran(int idPinjaman) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tabelangsuran.getModel();
        model.setRowCount(0);

        int nomor = 1;
        for (AngsuranDAO.AngsuranRow row : angsuranDAO.getRiwayatAngsuran(idPinjaman)) {
            model.addRow(new Object[]{
                nomor++,
                row.angsuranKe(),
                row.tanggalBayar(),
                formatRupiah(row.jumlahBayar()),
                row.status()
            });
        }
    }

    private void kosongkanTabelAngsuran() {
        DefaultTableModel model = (DefaultTableModel) tabelangsuran.getModel();
        model.setRowCount(0);
    }

    private BigDecimal parseNominal(String value) {
        if (value == null || value.isBlank()) {
            return BigDecimal.ZERO;
        }

        String cleaned = value
                .replace("Rp", "")
                .replace("rp", "")
                .replace(".", "")
                .replace(",", ".")
                .trim();

        try {
            return new BigDecimal(cleaned);
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private int parseInteger(String value) {
        if (value == null || value.isBlank()) {
            return 0;
        }

        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException ex) {
            return 0;
        }
    }

    private String formatRupiah(BigDecimal value) {
        BigDecimal angka = value == null ? BigDecimal.ZERO : value;
        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        format.setMaximumFractionDigits(0);
        return format.format(angka);
    }

    private String formatAngkaPlain(BigDecimal value) {
        BigDecimal angka = value == null ? BigDecimal.ZERO : value;
        return angka.stripTrailingZeros().toPlainString();
    }

    private void resetFormAngsuran() {
        cbbnopinjaman.setSelectedItem("");
        tnamaang.setText("");
        tang.setText("");
        tglangs.setDate(new Date());
        tjmlang.setText("");
        tketang.setText("");
        lblsisasimpanan.setText("0");
        kosongkanTabelAngsuran();
        cbbnopinjaman.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnresetang;
    private javax.swing.JButton btnsimpanang;
    private javax.swing.JComboBox<String> cbbnopinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsisasimpanan;
    private javax.swing.JTable tabelangsuran;
    private javax.swing.JTextField tang;
    private com.toedter.calendar.JDateChooser tglangs;
    private javax.swing.JTextField tjmlang;
    private javax.swing.JTextField tketang;
    private javax.swing.JTextField tnamaang;
    // End of variables declaration//GEN-END:variables
}
