/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.LaporanDAO;
import dao.JasperReportDAO;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.print.PrinterException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sabil
 */
public class Laporan extends javax.swing.JPanel {
    private final LaporanDAO laporanDAO = new LaporanDAO();
    private final JasperReportDAO jasperReportDAO = new JasperReportDAO();
    private String jenisLaporan = "anggota";
    private JTable tabelPreview;
    private JEditorPane previewHtml;
    private Object jasperPrintPreview;
    private boolean previewJasperAktif;

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        setupPreviewTable();
        muatJenisSimpanan();
        Rbtgl.setSelected(true);
        BtCetak.addActionListener(e -> cetakLaporan());
        BtExport.addActionListener(e -> exportLaporan());
        pilihLaporan("anggota");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bglaporan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtLpranggota = new javax.swing.JButton();
        BtLprSimpanan = new javax.swing.JButton();
        BtLprPinjaman = new javax.swing.JButton();
        BtLprangsuran = new javax.swing.JButton();
        BtLprtransaksi = new javax.swing.JButton();
        BtLprSHU = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtTglawal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dtTglakhir = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        CbSimpanan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Rbtgl = new javax.swing.JRadioButton();
        Rbnma = new javax.swing.JRadioButton();
        BtPreview = new javax.swing.JButton();
        BtCetak = new javax.swing.JButton();
        BtExport = new javax.swing.JButton();
        PreviewPanel = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PILIH LAPORAN");

        BtLpranggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtLpranggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-docs.png"))); // NOI18N
        BtLpranggota.setText("Laporan Data Anggota");
        BtLpranggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtLpranggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLpranggotaActionPerformed(evt);
            }
        });

        BtLprSimpanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtLprSimpanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-docs.png"))); // NOI18N
        BtLprSimpanan.setText("Laporan Simpanan");
        BtLprSimpanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtLprSimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLprSimpananActionPerformed(evt);
            }
        });

        BtLprPinjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtLprPinjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-docs.png"))); // NOI18N
        BtLprPinjaman.setText("Laporan Pinjaman");
        BtLprPinjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtLprPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLprPinjamanActionPerformed(evt);
            }
        });

        BtLprangsuran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtLprangsuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-docs.png"))); // NOI18N
        BtLprangsuran.setText("Laporan Angsuran");
        BtLprangsuran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtLprangsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLprangsuranActionPerformed(evt);
            }
        });

        BtLprtransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtLprtransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-docs.png"))); // NOI18N
        BtLprtransaksi.setText("Laporan Transaksi");
        BtLprtransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtLprtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLprtransaksiActionPerformed(evt);
            }
        });

        BtLprSHU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtLprSHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-docs.png"))); // NOI18N
        BtLprSHU.setText("Laporan SHU");
        BtLprSHU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtLprSHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLprSHUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtLpranggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtLprSimpanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(BtLprPinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(BtLprangsuran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(BtLprtransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(BtLprSHU, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtLpranggota, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtLprSimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtLprPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtLprangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtLprtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtLprSHU, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("FILTER LAPORAN");

        jLabel3.setText("Tanggal Awal");

        dtTglawal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Tanggal Akhir");

        dtTglakhir.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Jenis Simpanan");

        CbSimpanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- pilih --" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Urutkan Berdasarkan");

        Bglaporan.add(Rbtgl);
        Rbtgl.setText("Tanggal");

        Bglaporan.add(Rbnma);
        Rbnma.setText("Nama");

        BtPreview.setText("Preview");
        BtPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPreviewActionPerformed(evt);
            }
        });

        BtCetak.setText("Cetak");

        BtExport.setText("Export");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dtTglawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtTglakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbSimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtExport)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Rbtgl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rbnma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtTglawal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtTglakhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbSimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rbtgl)
                    .addComponent(Rbnma))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtPreview)
                    .addComponent(BtCetak)
                    .addComponent(BtExport))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        PreviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        PreviewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PreviewPanel.setOpaque(false);

        javax.swing.GroupLayout PreviewPanelLayout = new javax.swing.GroupLayout(PreviewPanel);
        PreviewPanel.setLayout(PreviewPanelLayout);
        PreviewPanelLayout.setHorizontalGroup(
            PreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        PreviewPanelLayout.setVerticalGroup(
            PreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtLpranggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLpranggotaActionPerformed
        pilihLaporan("anggota");
    }//GEN-LAST:event_BtLpranggotaActionPerformed

    private void BtLprSimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLprSimpananActionPerformed
        pilihLaporan("simpanan");
    }//GEN-LAST:event_BtLprSimpananActionPerformed

    private void BtLprPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLprPinjamanActionPerformed
        pilihLaporan("pinjaman");
    }//GEN-LAST:event_BtLprPinjamanActionPerformed

    private void BtLprangsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLprangsuranActionPerformed
        pilihLaporan("angsuran");
    }//GEN-LAST:event_BtLprangsuranActionPerformed

    private void BtLprtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLprtransaksiActionPerformed
        pilihLaporan("transaksi");
    }//GEN-LAST:event_BtLprtransaksiActionPerformed

    private void BtLprSHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLprSHUActionPerformed
        pilihLaporan("shu");
    }//GEN-LAST:event_BtLprSHUActionPerformed

    private void BtPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPreviewActionPerformed
        previewLaporan();
    }//GEN-LAST:event_BtPreviewActionPerformed

    private void setupPreviewTable() {
        tabelPreview = new JTable();
        tabelPreview.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        previewHtml = new JEditorPane();
        previewHtml.setContentType("text/html");
        previewHtml.setEditable(false);
        previewHtml.setBackground(java.awt.Color.WHITE);
        PreviewPanel.setLayout(new BorderLayout());
        PreviewPanel.removeAll();
        PreviewPanel.add(new JScrollPane(previewHtml), BorderLayout.CENTER);
        PreviewPanel.revalidate();
        PreviewPanel.repaint();
    }

    private void pilihLaporan(String laporan) {
        jenisLaporan = laporan;
        CbSimpanan.setEnabled("simpanan".equals(laporan));
        previewLaporan();
    }

    private void muatJenisSimpanan() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- semua --");

        try {
            for (String jenis : laporanDAO.getJenisSimpanan()) {
                model.addElement(jenis);
            }
        } catch (SQLException | RuntimeException ex) {
            model.addElement("Simpanan Wajib");
            model.addElement("Simpanan Pokok");
        }

        CbSimpanan.setModel(model);
    }

    private void previewLaporan() {
        if ("anggota".equals(jenisLaporan) && previewJasper("/resources/reports/ReportAnggota.jrxml")) {
            return;
        }

        if ("simpanan".equals(jenisLaporan) && previewJasper("/resources/reports/ReportSimpanan.jrxml")) {
            return;
        }

        if ("pinjaman".equals(jenisLaporan) && previewJasper("/resources/reports/ReportPinjaman.jrxml")) {
            return;
        }

        if ("angsuran".equals(jenisLaporan) && previewJasper("/resources/reports/ReportAngsuran.jrxml")) {
            return;
        }

        if ("transaksi".equals(jenisLaporan) && previewJasper("/resources/reports/ReportTransaksi.jrxml")) {
            return;
        }

        if ("shu".equals(jenisLaporan) && previewJasper("/resources/reports/ReportSHU.jrxml")) {
            return;
        }

        try {
            previewJasperAktif = false;
            jasperPrintPreview = null;
            LaporanDAO.TabelLaporan data = laporanDAO.getLaporan(buatFilterLaporan());
            tabelPreview.setModel(tableDataToTableModel(data));
            tampilkanPreviewHtml();
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat laporan.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private boolean previewJasper(String reportPath) {
        try (java.io.InputStream reportStream = getClass().getResourceAsStream(reportPath)) {
            jasperPrintPreview = jasperReportDAO.buatLaporan(reportStream, buatParameterJasper());
            Component viewer = buatJasperViewer(jasperPrintPreview);

            PreviewPanel.removeAll();
            PreviewPanel.setLayout(new BorderLayout());
            PreviewPanel.add(viewer, BorderLayout.CENTER);
            PreviewPanel.revalidate();
            PreviewPanel.repaint();
            aturFitPageJasper(viewer);

            previewJasperAktif = true;
            tabelPreview.setModel(new DefaultTableModel(new Object[][]{{"JasperReport"}}, new String[]{"Preview"}));
            return true;
        } catch (ClassNotFoundException ex) {
            previewJasperAktif = false;
            jasperPrintPreview = null;
            JOptionPane.showMessageDialog(
                    this,
                    "Library JasperReports belum ada di classpath.\nTambahkan jasperreports.jar beserta dependency-nya ke folder lib.",
                    "JasperReport",
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        } catch (Exception ex) {
            previewJasperAktif = false;
            jasperPrintPreview = null;
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat preview JasperReport.\n" + pesanException(ex),
                    "JasperReport",
                    JOptionPane.ERROR_MESSAGE
            );
            return false;
        }
    }

    private void aturFitPageJasper(Component viewer) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            try {
                java.lang.reflect.Method fitPage = viewer.getClass().getMethod("setFitPageZoomRatio");
                fitPage.invoke(viewer);
            } catch (ReflectiveOperationException | RuntimeException ignored) {
                try {
                    java.lang.reflect.Method fitWidth = viewer.getClass().getMethod("setFitWidthZoomRatio");
                    fitWidth.invoke(viewer);
                } catch (ReflectiveOperationException | RuntimeException ignoredAgain) {
                    // Biarkan zoom default kalau versi Jasper tidak menyediakan mode fit.
                }
            }
        });
    }

    private Map<String, Object> buatParameterJasper() {
        LaporanDAO.Filter filter = buatFilterLaporan();
        Map<String, Object> parameter = new HashMap<>();
        parameter.put("TANGGAL_AWAL", filter.tanggalAwal());
        parameter.put("TANGGAL_AKHIR", filter.tanggalAkhir());
        parameter.put("JENIS_SIMPANAN", "-- semua --".equals(filter.jenisSimpanan()) ? null : filter.jenisSimpanan());
        parameter.put("ORDER_ANGGOTA", filter.urutNama() ? "nama ASC" : "tanggal_daftar ASC");
        parameter.put("ORDER_SIMPANAN", filter.urutNama() ? "a.nama ASC" : "s.tanggal ASC");
        parameter.put("ORDER_PINJAMAN", filter.urutNama() ? "a.nama ASC" : "p.tanggal_pinjaman ASC");
        parameter.put("ORDER_ANGSURAN", filter.urutNama() ? "a.nama ASC" : "ag.tanggal_bayar ASC");
        parameter.put("ORDER_TRANSAKSI", filter.urutNama() ? "a.nama ASC" : "t.tanggal ASC");
        return parameter;
    }

    private Component buatJasperViewer(Object jasperPrint) throws Exception {
        Class<?> jasperPrintClass = Class.forName("net.sf.jasperreports.engine.JasperPrint");
        Class<?> viewerClass = Class.forName("net.sf.jasperreports.swing.JRViewer");
        return (Component) viewerClass.getConstructor(jasperPrintClass).newInstance(jasperPrint);
    }

    private void tampilkanPreviewHtml() {
        if (previewHtml == null) {
            return;
        }

        previewHtml.setText(buatHtmlLaporan());
        previewHtml.setCaretPosition(0);
    }

    private LaporanDAO.Filter buatFilterLaporan() {
        java.sql.Date awal = dtTglawal.getDate() == null ? null : new java.sql.Date(dtTglawal.getDate().getTime());
        java.sql.Date akhir = dtTglakhir.getDate() == null ? null : new java.sql.Date(dtTglakhir.getDate().getTime());
        String jenis = CbSimpanan.getSelectedItem() == null ? "-- semua --" : CbSimpanan.getSelectedItem().toString();

        return new LaporanDAO.Filter(jenisLaporan, awal, akhir, jenis, Rbnma.isSelected());
    }

    private DefaultTableModel tableDataToTableModel(LaporanDAO.TabelLaporan data) {
        DefaultTableModel model = new DefaultTableModel();

        for (String column : data.columns()) {
            model.addColumn(column);
        }

        for (List<Object> dataRow : data.rows()) {
            Object[] row = new Object[dataRow.size()];
            for (int column = 0; column < dataRow.size(); column++) {
                Object value = dataRow.get(column);
                row[column] = value instanceof BigDecimal ? formatRupiah((BigDecimal) value) : value;
            }
            model.addRow(row);
        }

        return model;
    }

    private void cetakLaporan() {
        if (tabelPreview.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Preview laporan terlebih dahulu.", "Cetak", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (previewJasperAktif && jasperPrintPreview != null) {
                cetakJasperPreview();
                return;
            }

            boolean dicetak = previewHtml.print();
            if (dicetak) {
                JOptionPane.showMessageDialog(this, "Laporan berhasil dikirim ke printer.");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak laporan.\n" + ex.getMessage(), "Cetak Gagal", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak laporan Jasper.\n" + pesanException(ex), "Cetak Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cetakJasperPreview() throws Exception {
        Class<?> jasperPrintClass = Class.forName("net.sf.jasperreports.engine.JasperPrint");
        Class<?> printManagerClass = Class.forName("net.sf.jasperreports.engine.JasperPrintManager");
        java.lang.reflect.Method printReport = printManagerClass.getMethod("printReport", jasperPrintClass, boolean.class);
        printReport.invoke(null, jasperPrintPreview, true);
    }

    private void exportLaporan() {
        if (tabelPreview.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Preview laporan terlebih dahulu.", "Export", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export Laporan");
        chooser.setSelectedFile(new File("laporan_" + jenisLaporan + ".csv"));
        chooser.setFileFilter(new FileNameExtensionFilter("CSV File (*.csv)", "csv"));

        if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        if (!file.getName().toLowerCase().endsWith(".csv")) {
            file = new File(file.getParentFile(), file.getName() + ".csv");
        }

        try {
            exportTableToCsv(file);
            JOptionPane.showMessageDialog(this, "Laporan berhasil diexport.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Gagal export laporan.\n" + ex.getMessage(), "Export Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportTableToCsv(File file) throws IOException {
        TableModel model = tabelPreview.getModel();

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            for (int column = 0; column < model.getColumnCount(); column++) {
                writer.write(escapeCsv(model.getColumnName(column)));
                if (column < model.getColumnCount() - 1) writer.write(",");
            }
            writer.newLine();

            for (int row = 0; row < model.getRowCount(); row++) {
                for (int column = 0; column < model.getColumnCount(); column++) {
                    Object value = model.getValueAt(row, column);
                    writer.write(escapeCsv(value == null ? "" : value.toString()));
                    if (column < model.getColumnCount() - 1) writer.write(",");
                }
                writer.newLine();
            }
        }
    }

    private String buatHtmlLaporan() {
        StringBuilder html = new StringBuilder();
        html.append("<!doctype html><html><head><meta charset=\"UTF-8\"><title>")
                .append(escapeHtml(judulLaporan()))
                .append("</title>");
        html.append(styleLaporan());
        html.append("</head><body>");
        html.append("<div class=\"sheet\">");
        html.append("<h1>").append(escapeHtml(judulLaporan().toUpperCase())).append("</h1>");
        html.append("<div class=\"periode\">").append(escapeHtml(teksPeriode())).append("</div>");
        html.append(tableToHtml());
        html.append("<div class=\"meta\">Tanggal Cetak: ")
                .append(escapeHtml(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date())))
                .append("</div>");
        html.append("<div class=\"signature\">")
                .append("<div>").append(escapeHtml(teksTanggalTandaTangan())).append("</div>")
                .append("<div class=\"admin\">Admin</div>")
                .append("<div class=\"line\"></div>")
                .append("</div>");
        html.append("</div></body></html>");
        return html.toString();
    }

    private String styleLaporan() {
        return """
                <style>
                body{font-family:Arial,sans-serif;background:#fff;margin:0;padding:0;color:#111}
                .sheet{width:100%;min-height:100%;margin:0;background:#fff;border:1px solid #cfcfcf;padding:56px 44px;box-sizing:border-box}
                h1{font-size:20px;text-align:center;margin:0 0 8px;font-weight:700;letter-spacing:0}
                .periode{text-align:center;font-size:12px;margin-bottom:24px}
                table{border-collapse:collapse;width:100%;font-size:12px}
                th,td{border:1px solid #7d7d7d;padding:7px 8px;text-align:left;vertical-align:middle}
                th{background:#f3f3f3;text-align:center;font-weight:700}
                td.no{text-align:center;width:34px}
                td.money{text-align:right;white-space:nowrap}
                tr.total td{font-weight:700;background:#fafafa}
                .meta{margin-top:18px;font-size:11px;color:#555}
                .signature{width:210px;margin:34px 20px 0 auto;text-align:center;font-size:12px}
                .signature .admin{margin-top:22px}
                .signature .line{border-top:1px solid #222;width:128px;margin:42px auto 0}
                @page{size:A4;margin:14mm}
                @media print{body{background:#fff;padding:0}.sheet{width:auto;min-height:auto;border:1px solid #cfcfcf;margin:0;padding:20px}}
                </style>
                """;
    }

    private String tableToHtml() {
        TableModel model = tabelPreview.getModel();
        List<Integer> columns = kolomPreview();
        StringBuilder html = new StringBuilder("<table><thead><tr>");

        html.append("<th>No.</th>");
        for (Integer column : columns) {
            html.append("<th>").append(escapeHtml(model.getColumnName(column))).append("</th>");
        }
        html.append("</tr></thead><tbody>");

        for (int row = 0; row < model.getRowCount(); row++) {
            html.append("<tr>");
            html.append("<td class=\"no\">").append(row + 1).append("</td>");
            for (Integer column : columns) {
                Object value = model.getValueAt(row, column);
                String text = value == null ? "" : value.toString();
                html.append("<td");
                if (isKolomUang(model.getColumnName(column))) {
                    html.append(" class=\"money\"");
                }
                html.append(">").append(escapeHtml(text)).append("</td>");
            }
            html.append("</tr>");
        }

        html.append(barisTotal(columns));
        html.append("</tbody></table>");
        return html.toString();
    }

    private List<Integer> kolomPreview() {
        TableModel model = tabelPreview.getModel();
        List<Integer> columns = new ArrayList<>();

        for (int column = 0; column < model.getColumnCount(); column++) {
            String name = model.getColumnName(column);
            if ("simpanan".equals(jenisLaporan)
                    && ("Tanggal".equalsIgnoreCase(name) || "Keterangan".equalsIgnoreCase(name))) {
                continue;
            }
            columns.add(column);
        }

        return columns;
    }

    private String barisTotal(List<Integer> columns) {
        String[] targetColumns = kolomTotal();
        if (targetColumns.length == 0 || tabelPreview.getRowCount() == 0) {
            return "";
        }

        int totalCount = 0;
        for (String target : targetColumns) {
            if (cariKolom(target) >= 0) {
                totalCount++;
            }
        }

        StringBuilder html = new StringBuilder("<tr class=\"total\">");
        int headerCount = columns.size() + 1;
        int colspan = Math.max(1, headerCount - Math.max(1, totalCount));
        html.append("<td colspan=\"").append(colspan).append("\" class=\"money\">").append(escapeHtml(labelTotal())).append("</td>");

        int renderedTotals = 0;
        for (String target : targetColumns) {
            int column = cariKolom(target);
            if (column >= 0) {
                html.append("<td class=\"money\">").append(escapeHtml(formatRupiah(totalKolom(column)))).append("</td>");
                renderedTotals++;
            }
        }

        if (renderedTotals == 0) {
            html.append("<td></td>");
        }
        html.append("</tr>");
        return html.toString();
    }

    private String[] kolomTotal() {
        return switch (jenisLaporan) {
            case "simpanan" -> new String[]{"Nominal"};
            case "pinjaman", "angsuran", "neraca", "shu" -> new String[]{"Jumlah", "Nominal"};
            case "transaksi" -> new String[]{"Debet", "Kredit"};
            default -> new String[]{};
        };
    }

    private String labelTotal() {
        return switch (jenisLaporan) {
            case "simpanan" -> "Total Saldo:";
            case "transaksi" -> "Total:";
            case "pinjaman" -> "Total Pinjaman:";
            case "angsuran" -> "Total Angsuran:";
            case "neraca" -> "Total Neraca:";
            case "shu" -> "Total SHU:";
            default -> "Total:";
        };
    }

    private int cariKolom(String namaKolom) {
        TableModel model = tabelPreview.getModel();
        for (int column = 0; column < model.getColumnCount(); column++) {
            if (namaKolom.equalsIgnoreCase(model.getColumnName(column))) {
                return column;
            }
        }
        return -1;
    }

    private BigDecimal totalKolom(int column) {
        BigDecimal total = BigDecimal.ZERO;
        TableModel model = tabelPreview.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            total = total.add(parseRupiah(model.getValueAt(row, column)));
        }
        return total;
    }

    private BigDecimal parseRupiah(Object value) {
        if (value == null) {
            return BigDecimal.ZERO;
        }
        String angka = value.toString().replaceAll("[^0-9-]", "");
        if (angka.isBlank() || "-".equals(angka)) {
            return BigDecimal.ZERO;
        }
        return new BigDecimal(angka);
    }

    private boolean isKolomUang(String name) {
        return "Nominal".equalsIgnoreCase(name)
                || "Saldo".equalsIgnoreCase(name)
                || "Jumlah".equalsIgnoreCase(name)
                || "Debet".equalsIgnoreCase(name)
                || "Kredit".equalsIgnoreCase(name)
                || "Angsuran/Bulan".equalsIgnoreCase(name);
    }

    private String teksPeriode() {
        Date awal = dtTglawal.getDate();
        Date akhir = dtTglakhir.getDate();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

        if (awal == null && akhir == null) {
            return "Semua Periode";
        }
        if (awal == null) {
            return "Periode s/d " + format.format(akhir);
        }
        if (akhir == null) {
            return "Periode " + format.format(awal) + " s/d sekarang";
        }
        return "Periode " + format.format(awal) + " s/d " + format.format(akhir);
    }

    private String teksTanggalTandaTangan() {
        Locale indonesia = new Locale("id", "ID");
        return "Pemalang, " + new SimpleDateFormat("dd MMMM yyyy", indonesia).format(new Date());
    }

    private String judulLaporan() {
        return switch (jenisLaporan) {
            case "simpanan" -> "Laporan Simpanan";
            case "pinjaman" -> "Laporan Pinjaman";
            case "angsuran" -> "Laporan Angsuran";
            case "transaksi" -> "Laporan Transaksi";
            case "neraca" -> "Laporan Neraca";
            case "shu" -> "Laporan SHU";
            default -> "Laporan Data Anggota";
        };
    }

    private String formatRupiah(BigDecimal value) {
        BigDecimal angka = value == null ? BigDecimal.ZERO : value;
        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        format.setMaximumFractionDigits(0);
        return format.format(angka);
    }

    private String escapeCsv(String value) {
        String text = value == null ? "" : value;
        boolean perluQuote = text.contains(",") || text.contains("\"") || text.contains("\n") || text.contains("\r");
        text = text.replace("\"", "\"\"");
        return perluQuote ? "\"" + text + "\"" : text;
    }

    private String escapeHtml(String value) {
        String text = value == null ? "" : value;
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }

    private String pesanException(Throwable throwable) {
        Throwable cause = throwable;
        while (cause.getCause() != null) {
            cause = cause.getCause();
        }

        String message = cause.getMessage();
        if (message == null || message.isBlank()) {
            return cause.getClass().getName();
        }
        return cause.getClass().getName() + ": " + message;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Bglaporan;
    private javax.swing.JButton BtCetak;
    private javax.swing.JButton BtExport;
    private javax.swing.JButton BtLprPinjaman;
    private javax.swing.JButton BtLprSHU;
    private javax.swing.JButton BtLprSimpanan;
    private javax.swing.JButton BtLpranggota;
    private javax.swing.JButton BtLprangsuran;
    private javax.swing.JButton BtLprtransaksi;
    private javax.swing.JButton BtPreview;
    private javax.swing.JComboBox<String> CbSimpanan;
    private javax.swing.JPanel PreviewPanel;
    private javax.swing.JRadioButton Rbnma;
    private javax.swing.JRadioButton Rbtgl;
    private com.toedter.calendar.JDateChooser dtTglakhir;
    private com.toedter.calendar.JDateChooser dtTglawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
