/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import dao.UserDAO;
import utils.SesiLogin;

/**
 *
 * @author Rangga
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private static final String PREF_INGAT_LOGIN = "ingat_login";
    private static final String PREF_AKUN_LOGIN = "akun_login";
    private static final Preferences PREFS = Preferences.userNodeForPackage(Login.class);
    private final UserDAO userDAO = new UserDAO();
    private java.awt.Point dragStartPoint;

    /**
     * Creates new form Login
     */
    public Login() {
        applyLookAndFeel();
        initComponents();
        pfPassword.setText("");
        pfpw.setText("");
        pfconfirmpw.setText("");
        setupPlaceholder();
        setupTabIcon();
        setupFrameDrag();
        setupIngatSaya();
        setLocationRelativeTo(null);
        bt_quit.addActionListener(e -> System.exit(0));
    }

    private void setupPlaceholder() {
        jTextField1.setText("");
        jTextField1.putClientProperty("JTextField.placeholderText", "Email atau nama");
        pfPassword.putClientProperty("JTextField.placeholderText", "Password");
        pfPassword.putClientProperty("PasswordField.showRevealButton", true);
        tfnama.putClientProperty("JTextField.placeholderText", "Nama");
        tfemail.putClientProperty("JTextField.placeholderText", "Email");
        pfpw.putClientProperty("JTextField.placeholderText", "Password");
        pfpw.putClientProperty("PasswordField.showRevealButton", true);
        pfconfirmpw.putClientProperty("JTextField.placeholderText", "Konfirmasi password");
        pfconfirmpw.putClientProperty("PasswordField.showRevealButton", true);
    }

    private void setupFrameDrag() {
        java.awt.event.MouseAdapter dragAdapter = new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragStartPoint = evt.getPoint();
            }

            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if (dragStartPoint == null) {
                    return;
                }

                java.awt.Point screenPoint = evt.getLocationOnScreen();
                setLocation(screenPoint.x - dragStartPoint.x, screenPoint.y - dragStartPoint.y);
            }
        };

        jPanel3.addMouseListener(dragAdapter);
        jPanel3.addMouseMotionListener(dragAdapter);
        jLabel1.addMouseListener(dragAdapter);
        jLabel1.addMouseMotionListener(dragAdapter);
    }

    private void setupIngatSaya() {
        boolean ingatLogin = PREFS.getBoolean(PREF_INGAT_LOGIN, false);
        cbingatsaya.setSelected(ingatLogin);
        if (ingatLogin) {
            jTextField1.setText(PREFS.get(PREF_AKUN_LOGIN, ""));
            pfPassword.requestFocus();
        }

        cbingatsaya.addActionListener(e -> {
            if (!cbingatsaya.isSelected()) {
                hapusLoginTersimpan();
            }
        });
    }

    private void simpanLoginJikaPerlu(String akun) {
        if (cbingatsaya.isSelected()) {
            PREFS.putBoolean(PREF_INGAT_LOGIN, true);
            PREFS.put(PREF_AKUN_LOGIN, akun);
        } else {
            hapusLoginTersimpan();
        }
    }

    private void hapusLoginTersimpan() {
        PREFS.putBoolean(PREF_INGAT_LOGIN, false);
        PREFS.remove(PREF_AKUN_LOGIN);
    }

    private void setupTabIcon() {
        updateTabIcon();
        jTabbedPane1.addChangeListener(e -> updateTabIcon());
    }

    private void updateTabIcon() {
        String iconPath = jTabbedPane1.getSelectedIndex() == 1
                ? "/resources/images/SignUp_image.png"
                : "/resources/images/Login_image.png";
        java.net.URL iconUrl = getClass().getResource(iconPath);
        if (iconUrl != null) {
            Icon.setText("");
            Icon.setIcon(new javax.swing.ImageIcon(iconUrl));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plogin = new javax.swing.JPanel();
        pfPassword = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        cbingatsaya = new javax.swing.JCheckBox();
        psignup = new javax.swing.JPanel();
        pfpw = new javax.swing.JPasswordField();
        tfnama = new javax.swing.JTextField();
        btcreateaccount = new javax.swing.JButton();
        pfconfirmpw = new javax.swing.JPasswordField();
        tfemail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_quit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setOpaque(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        plogin.setOpaque(false);

        pfPassword.addActionListener(this::pfPasswordActionPerformed);

        bt_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_login.setText("Login");
        bt_login.addActionListener(this::bt_loginActionPerformed);

        cbingatsaya.setText("Ingat Saya");

        javax.swing.GroupLayout ploginLayout = new javax.swing.GroupLayout(plogin);
        plogin.setLayout(ploginLayout);
        ploginLayout.setHorizontalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ploginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbingatsaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ploginLayout.setVerticalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ploginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(cbingatsaya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", plogin);

        psignup.setOpaque(false);

        pfpw.addActionListener(this::pfpwActionPerformed);

        btcreateaccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btcreateaccount.setText("Create Account");
        btcreateaccount.addActionListener(this::btcreateaccountActionPerformed);

        pfconfirmpw.addActionListener(this::pfconfirmpwActionPerformed);

        javax.swing.GroupLayout psignupLayout = new javax.swing.GroupLayout(psignup);
        psignup.setLayout(psignupLayout);
        psignupLayout.setHorizontalGroup(
            psignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psignupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(psignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psignupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btcreateaccount))
                    .addGroup(psignupLayout.createSequentialGroup()
                        .addGroup(psignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfconfirmpw, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfpw, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        psignupLayout.setVerticalGroup(
            psignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pfconfirmpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sign Up", psignup);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Authorization");

        bt_quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/quit.png"))); // NOI18N
        bt_quit.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Login_image.png"))); // NOI18N
        Icon.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        String akun = inputLogin();
        String password = new String(pfPassword.getPassword()).trim();

        if (akun.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Email/nama dan password wajib diisi.",
                    "Login Gagal",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            UserDAO.LoginResult result = userDAO.login(akun, password);
            if (result != null) {
                if (bukaHalamanSetelahLogin(result)) {
                    simpanLoginJikaPerlu(akun);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Email/nama atau password salah.",
                        "Login Gagal",
                        JOptionPane.ERROR_MESSAGE
                );
                pfPassword.setText("");
                pfPassword.requestFocus();
            }
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Tidak bisa terhubung ke database.\n" + ex.getMessage(),
                    "Koneksi Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
            pfPassword.setText("");
            pfPassword.requestFocus();
        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private boolean bukaHalamanSetelahLogin(UserDAO.LoginResult result) {
        Integer idUser = result.idUser();
        Integer idAnggota = result.idAnggota();
        String nama = result.nama();
        String group = result.group();
        SesiLogin.masuk(idUser, idAnggota, nama, group);

        if ("Pengguna".equalsIgnoreCase(group)) {
            if (idAnggota == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Akun anggota belum dikaitkan dengan data anggota.\nHubungi Super Admin untuk mengisi No Anggota pada data user.",
                        "Login Anggota",
                        JOptionPane.WARNING_MESSAGE
                );
                SesiLogin.keluar();
                return false;
            }

            new DashboardAnggota(idAnggota, nama).setVisible(true);
            return true;
        }

        new Dashboard(nama, group).setVisible(true);
        return true;
    }

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        bt_loginActionPerformed(evt);
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void pfpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfpwActionPerformed
        pfconfirmpw.requestFocus();
    }//GEN-LAST:event_pfpwActionPerformed

    private void btcreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateaccountActionPerformed
        buatAkunBaru();
    }//GEN-LAST:event_btcreateaccountActionPerformed

    private void pfconfirmpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfconfirmpwActionPerformed
        buatAkunBaru();
    }//GEN-LAST:event_pfconfirmpwActionPerformed

    private String inputLogin() {
        String akun = jTextField1.getText().trim();
        return "Email".equalsIgnoreCase(akun) ? "" : akun;
    }

    private void buatAkunBaru() {
        String email = tfemail.getText().trim();
        String password = new String(pfpw.getPassword()).trim();
        String konfirmasi = new String(pfconfirmpw.getPassword()).trim();

        if (email.isEmpty() || password.isEmpty() || konfirmasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email dan password wajib diisi.", "Sign Up", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Format email belum benar.", "Sign Up", JOptionPane.WARNING_MESSAGE);
            tfemail.requestFocus();
            return;
        }

        if (!password.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(this, "Konfirmasi password tidak sama.", "Sign Up", JOptionPane.WARNING_MESSAGE);
            pfconfirmpw.setText("");
            pfconfirmpw.requestFocus();
            return;
        }

        try {
            int inserted = userDAO.tambahPengguna(namaDariEmail(email), email, password);
            if (inserted > 0) {
                JOptionPane.showMessageDialog(this, "Akun berhasil dibuat. Silakan login.");
                jTextField1.setText(email);
                pfPassword.setText("");
                tfemail.setText("");
                pfpw.setText("");
                pfconfirmpw.setText("");
                jTabbedPane1.setSelectedIndex(0);
                pfPassword.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Group Pengguna belum tersedia di database.", "Sign Up", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            if (ex.getMessage() != null && ex.getMessage().toLowerCase().contains("duplicate")) {
                JOptionPane.showMessageDialog(this, "Email sudah terdaftar.", "Sign Up", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal membuat akun.\n" + ex.getMessage(), "Sign Up", JOptionPane.ERROR_MESSAGE);
            }
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Tidak bisa terhubung ke database.\n" + ex.getMessage(), "Sign Up", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String namaDariEmail(String email) {
        int at = email.indexOf('@');
        if (at <= 0) {
            return email;
        }
        return email.substring(0, at);
    }

    public static void applyLookAndFeel() {
        try {
            Class<?> flatDarkLaf = Class.forName("com.formdev.flatlaf.themes.FlatMacDarkLaf");
            flatDarkLaf.getMethod("setup").invoke(null);
            javax.swing.UIManager.put("PasswordField.showRevealButton", true);
        } catch (ReflectiveOperationException | RuntimeException ex) {
            logger.log(java.util.logging.Level.WARNING, "FlatLaf tidak tersedia, memakai Look and Feel default.", ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_quit;
    private javax.swing.JButton btcreateaccount;
    private javax.swing.JCheckBox cbingatsaya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPasswordField pfconfirmpw;
    private javax.swing.JPasswordField pfpw;
    private javax.swing.JPanel plogin;
    private javax.swing.JPanel psignup;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfnama;
    // End of variables declaration//GEN-END:variables
}
