/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.AnggotaDAO;
import dao.JasperReportDAO;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rangga
 */
public class ManajemenAnggota extends javax.swing.JPanel {
    private final AnggotaDAO anggotaDAO = new AnggotaDAO();
    private final JasperReportDAO jasperReportDAO = new JasperReportDAO();

    /**
     * Creates new form manajemen_anggotaa
     */
    public ManajemenAnggota() {
        initComponents();
        setDetailAnggotaEnabled(false);
        aktifkanAksiManajemenAnggota();
        aktifkanSearchRealtime();
        loadDataAnggota();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAnggota = new javax.swing.JTable();
        DetailAnggota = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNIK = new javax.swing.JTextField();
        tfNamaanggota = new javax.swing.JTextField();
        tfTempatlahiranggota = new javax.swing.JTextField();
        tfAlamatanggota = new javax.swing.JTextField();
        tfNohpanggota = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfDivisianggota = new javax.swing.JTextField();
        tfJumlahPinjamananggota = new javax.swing.JTextField();
        tfJumlahsimpanananggota = new javax.swing.JTextField();
        tfTanggaldaftaranggota = new javax.swing.JTextField();
        tfStatusanggota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNoanggota = new javax.swing.JTextField();
        btTambahanggota = new javax.swing.JButton();
        btEditanggota = new javax.swing.JButton();
        btHapusanggota = new javax.swing.JButton();
        btcetakanggota = new javax.swing.JButton();
        btExportanggota = new javax.swing.JButton();

        tfSearch.addActionListener(this::tfSearchActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Search");

        tbAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No. Anggota", "NIK", "Nama", "No. HP", "Divisi", "Alamat", "Tgl daftar", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbAnggota);

        DetailAnggota.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Detail Anggota");

        jLabel3.setText("NIK");

        jLabel4.setText("Nama");

        jLabel5.setText("Tempat, Tgl Lahir");

        jLabel6.setText("Alamat");

        jLabel7.setText("No.Hp");

        tfNIK.setEditable(false);

        tfNamaanggota.setEditable(false);

        tfTempatlahiranggota.setEditable(false);

        tfAlamatanggota.setEditable(false);

        tfNohpanggota.setEditable(false);

        jLabel9.setText("Divisi/Departemen");

        jLabel10.setText("Status");

        jLabel11.setText("Tgl, Daftar");

        jLabel12.setText("Jumlah Simpanan");

        jLabel13.setText("Jumlah Pinjaman");

        tfDivisianggota.setEditable(false);

        tfJumlahPinjamananggota.setEditable(false);

        tfJumlahsimpanananggota.setEditable(false);

        tfTanggaldaftaranggota.setEditable(false);

        tfStatusanggota.setEditable(false);

        jLabel8.setText("No. Anggota");

        tfNoanggota.setEnabled(false);
        tfNoanggota.addActionListener(this::tfNoanggotaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNIK)
                    .addComponent(tfNamaanggota)
                    .addComponent(tfTempatlahiranggota)
                    .addComponent(tfAlamatanggota)
                    .addComponent(tfNohpanggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDivisianggota)
                            .addComponent(tfStatusanggota)
                            .addComponent(tfTanggaldaftaranggota)
                            .addComponent(tfJumlahsimpanananggota)
                            .addComponent(tfJumlahPinjamananggota, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNoanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfNoanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNamaanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfStatusanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfTempatlahiranggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTanggaldaftaranggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfAlamatanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJumlahsimpanananggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfDivisianggota)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfJumlahPinjamananggota)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfNohpanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout DetailAnggotaLayout = new javax.swing.GroupLayout(DetailAnggota);
        DetailAnggota.setLayout(DetailAnggotaLayout);
        DetailAnggotaLayout.setHorizontalGroup(
            DetailAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DetailAnggotaLayout.setVerticalGroup(
            DetailAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailAnggotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btTambahanggota.setBackground(new java.awt.Color(0, 51, 204));
        btTambahanggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTambahanggota.setForeground(new java.awt.Color(255, 255, 255));
        btTambahanggota.setText("Tambah");
        btTambahanggota.addActionListener(this::btTambahanggotaActionPerformed);

        btEditanggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEditanggota.setText("Edit");

        btHapusanggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHapusanggota.setText("Hapus");

        btcetakanggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btcetakanggota.setText("Cetak");

        btExportanggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExportanggota.setText("Export");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btTambahanggota)
                            .addGap(18, 18, 18)
                            .addComponent(btEditanggota)
                            .addGap(18, 18, 18)
                            .addComponent(btHapusanggota)
                            .addGap(18, 18, 18)
                            .addComponent(btcetakanggota)
                            .addGap(18, 18, 18)
                            .addComponent(btExportanggota)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(DetailAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btTambahanggota)
                        .addComponent(btEditanggota)
                        .addComponent(btHapusanggota)
                        .addComponent(btcetakanggota)
                        .addComponent(btExportanggota)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(DetailAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        loadDataAnggota(tfSearch.getText().trim());
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btTambahanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahanggotaActionPerformed
        FormPengisian formAnggota = new FormPengisian();
        formAnggota.setModeTambah();
        formAnggota.setOnDataSaved(this::loadDataAnggota);
        formAnggota.setVisible(true);
    }//GEN-LAST:event_btTambahanggotaActionPerformed

    private void tfNoanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoanggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoanggotaActionPerformed

    private void btEditanggotaActionPerformed(java.awt.event.ActionEvent evt) {
        String noAnggota = getNoAnggotaTerpilih();
        if (noAnggota.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Pilih data anggota yang akan diedit terlebih dahulu.",
                    "Edit Anggota",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        bukaFormEditAnggota(noAnggota);
    }

    private void btHapusanggotaActionPerformed(java.awt.event.ActionEvent evt) {
        String noAnggota = getNoAnggotaTerpilih();
        if (noAnggota.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Pilih data anggota yang akan dihapus terlebih dahulu.",
                    "Hapus Anggota",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int pilihan = JOptionPane.showConfirmDialog(
                this,
                "Hapus data anggota " + noAnggota + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (pilihan != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            anggotaDAO.deleteJikaSelesai(noAnggota);
            JOptionPane.showMessageDialog(this, "Data anggota berhasil dihapus.");
            loadDataAnggota(tfSearch.getText().trim());
            kosongkanDetailAnggota();
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menghapus data anggota.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void btcetakanggotaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Object jasperPrint;
            try (java.io.InputStream reportStream = getClass().getResourceAsStream("/resources/reports/ReportAnggota.jrxml")) {
                jasperPrint = jasperReportDAO.buatLaporanAnggota(reportStream);
            }

            cetakJasperReport(jasperPrint);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal mencetak data anggota.\n" + pesanException(ex),
                    "Cetak Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void cetakJasperReport(Object jasperPrint) throws Exception {
        Class<?> jasperPrintClass = Class.forName("net.sf.jasperreports.engine.JasperPrint");
        Class<?> printManagerClass = Class.forName("net.sf.jasperreports.engine.JasperPrintManager");
        java.lang.reflect.Method printReport = printManagerClass.getMethod("printReport", jasperPrintClass, boolean.class);
        printReport.invoke(null, jasperPrint, true);
    }

    private void btExportanggotaActionPerformed(java.awt.event.ActionEvent evt) {
        if (tbAnggota.getRowCount() == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Tidak ada data anggota yang bisa diexport.",
                    "Export Anggota",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export Data Anggota");
        fileChooser.setSelectedFile(new File("data_anggota.csv"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("CSV File (*.csv)", "csv"));

        int pilihan = fileChooser.showSaveDialog(this);
        if (pilihan != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = fileChooser.getSelectedFile();
        if (!file.getName().toLowerCase().endsWith(".csv")) {
            file = new File(file.getParentFile(), file.getName() + ".csv");
        }

        try {
            exportTableToCsv(file);
            JOptionPane.showMessageDialog(this, "Data anggota berhasil diexport.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal export data anggota.\n" + ex.getMessage(),
                    "Export Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void bukaFormEditAnggota(String noAnggota) {
        try {
            AnggotaDAO.AnggotaData anggota = anggotaDAO.getByNoAnggota(noAnggota);
            if (anggota == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Data anggota tidak ditemukan.",
                        "Edit Gagal",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            FormPengisian formAnggota = new FormPengisian();
            formAnggota.setModeEdit();
            formAnggota.isiDataAnggota(
                    anggota.noAnggota(),
                    anggota.nik(),
                    anggota.nama(),
                    anggota.tempatLahir(),
                    anggota.tanggalLahir(),
                    anggota.jenisKelamin(),
                    anggota.alamat(),
                    anggota.kotaKabupaten(),
                    anggota.noHp(),
                    anggota.divisi(),
                    anggota.tanggalDaftar()
            );
            formAnggota.setOnDataSaved(this::loadDataAnggota);
            formAnggota.setVisible(true);
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal membuka data anggota.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void loadDataAnggota() {
        loadDataAnggota("");
    }

    private void loadDataAnggota(String keyword) {
        DefaultTableModel model = (DefaultTableModel) tbAnggota.getModel();
        model.setRowCount(0);

        try {
            int nomor = 1;
            for (AnggotaDAO.AnggotaData anggota : anggotaDAO.search(keyword)) {
                tambahRowAnggota(model, nomor++, anggota);
            }
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data anggota.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void tambahRowAnggota(DefaultTableModel model, int nomor, AnggotaDAO.AnggotaData anggota) {
        Object[] row = new Object[model.getColumnCount()];

        for (int column = 0; column < model.getColumnCount(); column++) {
            String columnName = model.getColumnName(column).toLowerCase();

            if (columnName.equals("no")) {
                row[column] = nomor;
            } else if (columnName.contains("no. anggota") || columnName.contains("no anggota")) {
                row[column] = anggota.noAnggota();
            } else if (columnName.contains("nik")) {
                row[column] = anggota.nik();
            } else if (columnName.contains("nama")) {
                row[column] = anggota.nama();
            } else if (columnName.contains("tempat") || columnName.contains("lahir")) {
                row[column] = formatTempatTanggal(anggota.tempatLahir(), anggota.tanggalLahir());
            } else if (columnName.contains("hp")) {
                row[column] = anggota.noHp();
            } else if (columnName.contains("alamat")) {
                row[column] = anggota.alamat();
            } else if (columnName.contains("divisi") || columnName.contains("departemen")) {
                row[column] = anggota.divisi();
            } else if (columnName.contains("daftar")) {
                row[column] = anggota.tanggalDaftar();
            } else if (columnName.contains("status")) {
                row[column] = anggota.status();
            }
        }

        model.addRow(row);
    }

    private void aktifkanSearchRealtime() {
        tfSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cariAnggota();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                cariAnggota();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                cariAnggota();
            }

            private void cariAnggota() {
                loadDataAnggota(tfSearch.getText().trim());
            }
        });
    }

    private void aktifkanAksiManajemenAnggota() {
        btEditanggota.addActionListener(this::btEditanggotaActionPerformed);
        btHapusanggota.addActionListener(this::btHapusanggotaActionPerformed);
        btcetakanggota.addActionListener(this::btcetakanggotaActionPerformed);
        btExportanggota.addActionListener(this::btExportanggotaActionPerformed);

        tbAnggota.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                tampilkanDetailAnggotaTerpilih();
            }
        });

        tbAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    String noAnggota = getNoAnggotaTerpilih();
                    if (!noAnggota.isEmpty()) {
                        bukaFormEditAnggota(noAnggota);
                    }
                }
            }
        });
    }

    private void tampilkanDetailAnggotaTerpilih() {
        String noAnggota = getNoAnggotaTerpilih();
        if (noAnggota.isEmpty()) {
            kosongkanDetailAnggota();
            return;
        }

        tampilkanDetailAnggota(noAnggota);
    }

    private void tbAnggotaMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tbAnggota.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        int modelRow = tbAnggota.convertRowIndexToModel(selectedRow);
        String noAnggota = ambilNilaiTabel(modelRow, 1, "");
        tampilkanDetailAnggota(noAnggota);

        if (evt.getClickCount() == 2 && !noAnggota.isEmpty()) {
            bukaFormEditAnggota(noAnggota);
        }
    }

    private void tampilkanDetailAnggota(String noAnggota) {
        try {
            AnggotaDAO.DetailAnggota detail = anggotaDAO.getDetail(noAnggota);
            if (detail == null) {
                return;
            }

            tfNoanggota.setText(detail.noAnggota());
            setDetailNIK(detail.nik());
            tfNamaanggota.setText(detail.nama());
            tfTempatlahiranggota.setText(formatTempatTanggal(detail.tempatLahir(), detail.tanggalLahir()));
            tfAlamatanggota.setText(detail.alamat());
            tfNohpanggota.setText(detail.noHp());
            tfDivisianggota.setText(detail.divisi());
            tfStatusanggota.setText(detail.status());
            tfTanggaldaftaranggota.setText(String.valueOf(detail.tanggalDaftar()));
            tfJumlahsimpanananggota.setText(detail.totalSimpanan().toPlainString());
            tfJumlahPinjamananggota.setText(detail.totalPinjaman().toPlainString());
            setDetailAnggotaEnabled(false);
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat detail anggota.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private String formatTempatTanggal(String tempat, Date tanggal) {
        String tempatLahir = tempat == null ? "" : tempat;
        if (tanggal == null) {
            return tempatLahir;
        }

        String tanggalIndonesia = new SimpleDateFormat("dd MMMM yyyy", new Locale("id", "ID"))
                .format(tanggal)
                .toLowerCase(new Locale("id", "ID"));
        return tempatLahir + ", " + tanggalIndonesia;
    }

    private void exportTableToCsv(File file) throws IOException {
        TableModel model = tbAnggota.getModel();
        String delimiter = ";";

        try (BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(
                new FileOutputStream(file), StandardCharsets.UTF_8))) {
            writer.write('\ufeff');
            writer.write("sep=");
            writer.write(delimiter);
            writer.newLine();

            for (int viewColumn = 0; viewColumn < tbAnggota.getColumnCount(); viewColumn++) {
                int modelColumn = tbAnggota.convertColumnIndexToModel(viewColumn);
                writer.write(escapeCsv(model.getColumnName(modelColumn), delimiter));
                if (viewColumn < tbAnggota.getColumnCount() - 1) {
                    writer.write(delimiter);
                }
            }
            writer.newLine();

            for (int viewRow = 0; viewRow < tbAnggota.getRowCount(); viewRow++) {
                int modelRow = tbAnggota.convertRowIndexToModel(viewRow);
                for (int viewColumn = 0; viewColumn < tbAnggota.getColumnCount(); viewColumn++) {
                    int modelColumn = tbAnggota.convertColumnIndexToModel(viewColumn);
                    Object value = model.getValueAt(modelRow, modelColumn);
                    String columnName = model.getColumnName(modelColumn);
                    writer.write(escapeCsv(formatCsvValue(value, columnName), delimiter));
                    if (viewColumn < tbAnggota.getColumnCount() - 1) {
                        writer.write(delimiter);
                    }
                }
                writer.newLine();
            }
        }
    }

    private String formatCsvValue(Object value, String columnName) {
        if (value instanceof Date tanggal) {
            return new SimpleDateFormat("dd-MM-yyyy").format(tanggal);
        }

        String text = value == null ? "" : value.toString().trim();
        return isExcelTextColumn(columnName) ? toExcelText(text) : text;
    }

    private boolean isExcelTextColumn(String columnName) {
        String name = columnName == null ? "" : columnName.toLowerCase();
        return name.contains("nik") || name.contains("hp") || name.contains("no. anggota")
                || name.contains("no anggota");
    }

    private String toExcelText(String text) {
        if (text.isEmpty()) {
            return "";
        }

        return "=\"" + text.replace("\"", "\"\"") + "\"";
    }

    private String escapeCsv(String value, String delimiter) {
        String text = value == null ? "" : value;
        boolean perluQuote = text.contains(delimiter) || text.contains("\"")
                || text.contains("\n") || text.contains("\r");
        text = text.replace("\"", "\"\"");
        return perluQuote ? "\"" + text + "\"" : text;
    }

    private String pesanException(Throwable throwable) {
        Throwable cause = throwable;
        while (cause.getCause() != null) {
            cause = cause.getCause();
        }

        String message = cause.getMessage();
        if (message == null || message.isBlank()) {
            return cause.getClass().getName();
        }
        return cause.getClass().getName() + ": " + message;
    }

    private void setDetailNIK(String nik) {
        JTextField field = getDetailNIKField();
        if (field != null) {
            field.setText(nik == null ? "" : nik);
        }
    }

    private JTextField getDetailNIKField() {
        try {
            java.lang.reflect.Field field = getClass().getDeclaredField("tfNIK");
            field.setAccessible(true);
            Object value = field.get(this);
            return value instanceof JTextField ? (JTextField) value : null;
        } catch (NoSuchFieldException | IllegalAccessException ex) {
            return null;
        }
    }

    private String ambilNilaiTabel(int row, int column, String nilaiDefault) {
        Object value = tbAnggota.getModel().getValueAt(row, column);
        if (value == null || value.toString().trim().isEmpty()) {
            return nilaiDefault;
        }

        return value.toString();
    }

    private Date parseTanggal(String tanggal) {
        if (tanggal == null || tanggal.isBlank()) {
            return null;
        }

        String[] formats = {"yyyy-MM-dd", "dd-MM-yyyy", "dd/MM/yyyy"};
        for (String format : formats) {
            try {
                return new SimpleDateFormat(format).parse(tanggal);
            } catch (ParseException ex) {
                // Coba format tanggal berikutnya.
            }
        }

        return null;
    }

    private String getNoAnggotaTerpilih() {
        int selectedRow = tbAnggota.getSelectedRow();
        if (selectedRow != -1) {
            int modelRow = tbAnggota.convertRowIndexToModel(selectedRow);
            return ambilNilaiTabel(modelRow, 1, "").trim();
        }

        return tfNIK.getText().trim();
    }

    private void kosongkanDetailAnggota() {
        tfNIK.setText("");
        setDetailNIK("");
        tfNamaanggota.setText("");
        tfTempatlahiranggota.setText("");
        tfAlamatanggota.setText("");
        tfNohpanggota.setText("");
        tfDivisianggota.setText("");
        tfStatusanggota.setText("");
        tfTanggaldaftaranggota.setText("");
        tfJumlahsimpanananggota.setText("");
        tfJumlahPinjamananggota.setText("");
    }

    private void setDetailAnggotaEnabled(boolean enabled) {
        tfNIK.setEnabled(enabled);
        JTextField nikField = getDetailNIKField();
        if (nikField != null) {
            nikField.setEnabled(enabled);
        }
        tfNamaanggota.setEnabled(enabled);
        tfTempatlahiranggota.setEnabled(enabled);
        tfAlamatanggota.setEnabled(enabled);
        tfNohpanggota.setEnabled(enabled);
        tfDivisianggota.setEnabled(enabled);
        tfStatusanggota.setEnabled(enabled);
        tfTanggaldaftaranggota.setEnabled(enabled);
        tfJumlahsimpanananggota.setEnabled(enabled);
        tfJumlahPinjamananggota.setEnabled(enabled);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailAnggota;
    private javax.swing.JButton btEditanggota;
    private javax.swing.JButton btExportanggota;
    private javax.swing.JButton btHapusanggota;
    private javax.swing.JButton btTambahanggota;
    private javax.swing.JButton btcetakanggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAnggota;
    private javax.swing.JTextField tfAlamatanggota;
    private javax.swing.JTextField tfDivisianggota;
    private javax.swing.JTextField tfJumlahPinjamananggota;
    private javax.swing.JTextField tfJumlahsimpanananggota;
    private javax.swing.JTextField tfNIK;
    private javax.swing.JTextField tfNamaanggota;
    private javax.swing.JTextField tfNoanggota;
    private javax.swing.JTextField tfNohpanggota;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStatusanggota;
    private javax.swing.JTextField tfTanggaldaftaranggota;
    private javax.swing.JTextField tfTempatlahiranggota;
    // End of variables declaration//GEN-END:variables
}
