/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.SimpananDAO;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ManajemenSimpanan extends javax.swing.JPanel {
    private final SimpananDAO simpananDAO = new SimpananDAO();
    private final List<String> pilihanAnggota = new ArrayList<>();
    private final Map<String, String> namaAnggotaByPilihan = new HashMap<>();
    private boolean sedangFilterAnggota = false;

    /**
     * Creates new form manajemen_simpanan
     */
    public ManajemenSimpanan() {
        initComponents();
        tfNama.setEditable(false);
        muatJenisSimpanan();
        muatComboAnggota();
        aktifkanNominalSimpananWajib();
        aktifkanSearchComboAnggota();
        aktifkanSearchSimpanan();
        btReset.addActionListener(e -> resetFormSimpanan());
        cbNoanggota.setSelectedItem("");
        kosongkanTabelSimpanan();
    }

    private void aktifkanNominalSimpananWajib() {
        cbjenis.addActionListener(e -> terapkanNominalSimpananWajib());
        terapkanNominalSimpananWajib();
    }

    private void terapkanNominalSimpananWajib() {
        String jenisSimpanan = cbjenis.getSelectedItem() == null ? "" : cbjenis.getSelectedItem().toString();
        if ("Simpanan Wajib".equalsIgnoreCase(jenisSimpanan)) {
            BigDecimal nominalWajib = PengaturanSistem.muat().simpananWajib();
            tfNominal.setText(PengaturanSistem.formatUang(nominalWajib));
            tfNominal.setEditable(false);
            return;
        }

        boolean sebelumnyaTerkunci = !tfNominal.isEditable();
        tfNominal.setEditable(true);
        if (!tfNominal.getText().isBlank() && sebelumnyaTerkunci) {
            tfNominal.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        tfNama = new javax.swing.JTextField();
        cbjenis = new javax.swing.JComboBox<>();
        tfNominal = new javax.swing.JTextField();
        tfKeterangan = new javax.swing.JTextField();
        cbNoanggota = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSimpanan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbltotalsaldosimpanan = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("No. Anggota");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Simpanan");

        jLabel5.setText("Nominal");

        jLabel6.setText("Keterangan");

        btSimpan.setBackground(new java.awt.Color(0, 51, 204));
        btSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/diskette.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(153, 0, 0));
        btReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/undowhite.png"))); // NOI18N
        btReset.setText("Reset");

        cbjenis.setEditable(true);
        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Simpanan Wajib", "Simpanan Pokok" }));

        cbNoanggota.setEditable(true);
        cbNoanggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Input Simpanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNama)
                            .addComponent(cbjenis, 0, 129, Short.MAX_VALUE)
                            .addComponent(tfNominal)
                            .addComponent(tfKeterangan)
                            .addComponent(cbNoanggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNoanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNama)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbjenis)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNominal)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfKeterangan)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Daftar Simpanan Anggota");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Search :");

        tbSimpanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbSimpanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Tanggal", "Jenis Simpanan", "Nominal", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSimpanan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSimpanan);
        if (tbSimpanan.getColumnModel().getColumnCount() > 0) {
            tbSimpanan.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Total Saldo Simpanan :");

        lbltotalsaldosimpanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltotalsaldosimpanan.setText("Rp. 0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalsaldosimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbltotalsaldosimpanan))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        simpanDataSimpanan();
    }//GEN-LAST:event_btSimpanActionPerformed

    private void simpanDataSimpanan() {
        String noAnggota = getNoAnggotaTerpilih();
        String jenisSimpanan = cbjenis.getSelectedItem() == null ? "" : cbjenis.getSelectedItem().toString();
        BigDecimal nominal = "Simpanan Wajib".equalsIgnoreCase(jenisSimpanan)
                ? PengaturanSistem.muat().simpananWajib()
                : parseNominal(tfNominal.getText());

        if (noAnggota.isEmpty() || tfNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih No. Anggota terlebih dahulu.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jenisSimpanan.equals("--Pilih--") || jenisSimpanan.isBlank()) {
            JOptionPane.showMessageDialog(this, "Pilih jenis simpanan terlebih dahulu.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (nominal.compareTo(BigDecimal.ZERO) <= 0) {
            JOptionPane.showMessageDialog(this, "Nominal simpanan harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            simpananDAO.insert(noAnggota, jenisSimpanan, nominal, tfKeterangan.getText().trim());
            JOptionPane.showMessageDialog(this, "Data simpanan berhasil disimpan.");
            resetFormSimpanan();
            loadDataSimpanan(jTextField5.getText().trim());
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menyimpan data simpanan.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void muatJenisSimpanan() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("--Pilih--");

        try {
            for (String jenis : simpananDAO.getJenisSimpanan()) {
                model.addElement(jenis);
            }

            cbjenis.setModel(model);
        } catch (SQLException | RuntimeException ex) {
            cbjenis.setModel(new DefaultComboBoxModel<>(new String[]{"--Pilih--", "Simpanan Wajib", "Simpanan Pokok"}));
        }
    }

    private void loadDataSimpanan() {
        loadDataSimpanan("");
    }

    private void loadDataSimpanan(String keyword) {
        String noAnggotaFilter = getNoAnggotaTerpilih();
        if (noAnggotaFilter.isEmpty()) {
            kosongkanTabelSimpanan();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbSimpanan.getModel();
        model.setRowCount(0);

        BigDecimal totalSaldo = BigDecimal.ZERO;

        try {
            int nomor = 1;
            for (SimpananDAO.SimpananRow row : simpananDAO.searchByAnggota(noAnggotaFilter, keyword)) {
                totalSaldo = totalSaldo.add(row.nominal());

                model.addRow(new Object[]{
                    nomor++,
                    row.tanggal(),
                    row.namaJenis(),
                    formatRupiah(row.nominal()),
                    formatRupiah(row.saldo())
                });
            }

            lbltotalsaldosimpanan.setText(formatRupiah(totalSaldo));
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data simpanan.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void kosongkanTabelSimpanan() {
        DefaultTableModel model = (DefaultTableModel) tbSimpanan.getModel();
        model.setRowCount(0);
        lbltotalsaldosimpanan.setText(formatRupiah(BigDecimal.ZERO));
    }

    private void muatComboAnggota() {
        pilihanAnggota.clear();
        namaAnggotaByPilihan.clear();

        try {
            for (SimpananDAO.AnggotaPilihan anggota : simpananDAO.getAnggotaAktif()) {
                String pilihan = anggota.pilihan();

                pilihanAnggota.add(pilihan);
                namaAnggotaByPilihan.put(pilihan, anggota.nama());
            }

            isiModelComboAnggota(pilihanAnggota, "");
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data anggota.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void aktifkanSearchComboAnggota() {
        JTextField editor = (JTextField) cbNoanggota.getEditor().getEditorComponent();

        cbNoanggota.addActionListener(e -> isiNamaAnggotaTerpilih());
        editor.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterAnggota();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterAnggota();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterAnggota();
            }

            private void filterAnggota() {
                if (sedangFilterAnggota) {
                    return;
                }

                SwingUtilities.invokeLater(() -> {
                    String keyword = editor.getText();
                    List<String> hasil = new ArrayList<>();

                    for (String pilihan : pilihanAnggota) {
                        if (pilihan.toLowerCase().contains(keyword.toLowerCase())) {
                            hasil.add(pilihan);
                        }
                    }

                    isiModelComboAnggota(hasil, keyword);
                    if (!keyword.isBlank()) {
                        cbNoanggota.showPopup();
                    }
                });
            }
        });
    }

    private void aktifkanSearchSimpanan() {
        jTextField5.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cariSimpanan();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                cariSimpanan();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                cariSimpanan();
            }

            private void cariSimpanan() {
                loadDataSimpanan(jTextField5.getText().trim());
            }
        });
    }

    private void isiModelComboAnggota(List<String> data, String teksEditor) {
        sedangFilterAnggota = true;

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        cbNoanggota.setModel(model);
        cbNoanggota.setSelectedItem(teksEditor);

        sedangFilterAnggota = false;
    }

    private void isiNamaAnggotaTerpilih() {
        Object selectedItem = cbNoanggota.getSelectedItem();
        if (selectedItem == null) {
            tfNama.setText("");
            kosongkanTabelSimpanan();
            return;
        }

        String pilihan = selectedItem.toString();
        if (pilihan.isBlank()) {
            tfNama.setText("");
            kosongkanTabelSimpanan();
            return;
        }

        tfNama.setText(namaAnggotaByPilihan.getOrDefault(pilihan, ""));
        if (tfNama.getText().trim().isEmpty()) {
            kosongkanTabelSimpanan();
            return;
        }

        loadDataSimpanan(jTextField5.getText().trim());
    }

    private String getNoAnggotaTerpilih() {
        Object selectedItem = cbNoanggota.getSelectedItem();
        if (selectedItem == null) {
            return "";
        }

        String pilihan = selectedItem.toString().trim();
        int separatorIndex = pilihan.indexOf(" - ");
        if (separatorIndex > -1) {
            return pilihan.substring(0, separatorIndex).trim();
        }

        return pilihan;
    }

    private BigDecimal parseNominal(String value) {
        if (value == null || value.isBlank()) {
            return BigDecimal.ZERO;
        }

        String cleaned = value
                .replace("Rp", "")
                .replace("rp", "")
                .replace(".", "")
                .replace(",", ".")
                .trim();

        try {
            return new BigDecimal(cleaned);
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private String formatRupiah(BigDecimal value) {
        return PengaturanSistem.formatUang(value);
    }

    private void resetFormSimpanan() {
        cbNoanggota.setSelectedItem("");
        tfNama.setText("");
        cbjenis.setSelectedIndex(0);
        tfNominal.setText("");
        tfNominal.setEditable(true);
        tfKeterangan.setText("");
        kosongkanTabelSimpanan();
        cbNoanggota.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSimpan;
    private javax.swing.JComboBox<String> cbNoanggota;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbltotalsaldosimpanan;
    private javax.swing.JTable tbSimpanan;
    private javax.swing.JTextField tfKeterangan;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNominal;
    // End of variables declaration//GEN-END:variables
}
