/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AgunanDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author sabil
 */
public class ManajemenAgunan extends javax.swing.JFrame {

    private final AgunanDAO agunanDAO = new AgunanDAO();
    private final SimpleDateFormat tanggalFormat = new SimpleDateFormat("dd/MM/yyyy");
    private final List<AgunanDAO.AgunanRow> dataAgunan = new ArrayList<>();

    /**
     * Creates new form ManajemenAgunanBaru
     */
    public ManajemenAgunan() {
        initComponents();
        setupAgunan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        cbFilterJenis = new javax.swing.JComboBox<>();
        cbFilterStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtHapus = new javax.swing.JButton();
        BtExport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        cbFilterJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Jenis", " " }));

        cbFilterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Status" }));

        jLabel1.setText("Filter Data");

        jButton1.setText("Edit");

        BtHapus.setText("Hapus");

        BtExport.setText("Export");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFilterJenis, 0, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTambah)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btTambah)
                    .addComponent(cbFilterJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(BtHapus)
                    .addComponent(BtExport))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Peminjaman", "No Anggota", "Nama Anggota", "Jenis Agunan", "Nilai Taksir", "Tanggal", "Status", "Deskripsi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        bukaFormTambah();
    }//GEN-LAST:event_btTambahActionPerformed

    private void setupAgunan() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setupTable();
        setupEvents();
        muatAwal();
        getContentPane().revalidate();
        getContentPane().repaint();
    }

    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"No", "Kode Peminjaman", "No Anggota", "Nama Anggota",
                    "Jenis Agunan", "Nilai Taksir", "Tanggal", "Status", "Deskripsi"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(model);
        jTable1.setRowHeight(26);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);

        TableColumnModel columns = jTable1.getColumnModel();
        columns.getColumn(0).setPreferredWidth(40);
        columns.getColumn(1).setPreferredWidth(120);
        columns.getColumn(2).setPreferredWidth(100);
        columns.getColumn(3).setPreferredWidth(150);
        columns.getColumn(4).setPreferredWidth(130);
        columns.getColumn(5).setPreferredWidth(120);
        columns.getColumn(6).setPreferredWidth(90);
        columns.getColumn(7).setPreferredWidth(90);
        columns.getColumn(8).setPreferredWidth(220);
    }

    private void setupEvents() {
        jButton1.addActionListener(e -> bukaFormEdit());
        BtHapus.addActionListener(e -> hapusData());
        cbFilterJenis.addActionListener(e -> muatData());
        cbFilterStatus.addActionListener(e -> muatData());

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2 && jTable1.getSelectedRow() >= 0) {
                    bukaFormEdit();
                }
            }
        });

        jTable1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    evt.consume();
                    bukaFormEdit();
                } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                    hapusData();
                }
            }
        });
    }

    private void muatAwal() {
        try {
            agunanDAO.pastikanTabelAgunan();
            muatFilter();
            muatData();
        } catch (SQLException ex) {
            tampilkanError("Tidak bisa memuat data agunan.", ex);
        }
    }

    private void muatFilter() throws SQLException {
        Object selectedJenis = cbFilterJenis.getSelectedItem();
        Object selectedStatus = cbFilterStatus.getSelectedItem();

        cbFilterJenis.removeAllItems();
        cbFilterJenis.addItem("Semua Jenis");
        for (String jenis : agunanDAO.getJenisAgunan()) {
            cbFilterJenis.addItem(jenis);
        }
        pilihComboJikaAda(cbFilterJenis, selectedJenis);

        cbFilterStatus.removeAllItems();
        cbFilterStatus.addItem("Semua Status");
        for (String status : agunanDAO.getStatusAgunan()) {
            cbFilterStatus.addItem(status);
        }
        pilihComboJikaAda(cbFilterStatus, selectedStatus);
    }

    private void muatData() {
        try {
            String jenis = ambilCombo(cbFilterJenis, "Semua Jenis");
            String status = ambilCombo(cbFilterStatus, "Semua Status");
            dataAgunan.clear();
            dataAgunan.addAll(agunanDAO.search(jenis, status));

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            int nomor = 1;
            for (AgunanDAO.AgunanRow row : dataAgunan) {
                model.addRow(new Object[]{
                    nomor++,
                    row.noPinjaman(),
                    row.noAnggota(),
                    row.namaAnggota(),
                    row.jenisAgunan(),
                    formatUang(row.nilaiTaksir()),
                    row.tanggal() == null ? "" : tanggalFormat.format(row.tanggal()),
                    row.status(),
                    row.deskripsi()
                });
            }
        } catch (SQLException ex) {
            tampilkanError("Tidak bisa memuat data agunan.", ex);
        }
    }

    private String ambilCombo(javax.swing.JComboBox<String> comboBox, String defaultValue) {
        Object selected = comboBox.getSelectedItem();
        if (selected == null || selected.toString().isBlank()) {
            return defaultValue;
        }
        return selected.toString();
    }

    private void bukaFormTambah() {
        FormPengisianAgunan form = new FormPengisianAgunan(this::refreshSetelahSimpan);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }

    private void bukaFormEdit() {
        AgunanDAO.AgunanRow row = getSelectedData();
        if (row == null) {
            JOptionPane.showMessageDialog(this, "Pilih data agunan yang akan diedit.");
            return;
        }

        FormPengisianAgunan form = new FormPengisianAgunan(row.idAgunan(), this::refreshSetelahSimpan);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }

    private void hapusData() {
        AgunanDAO.AgunanRow row = getSelectedData();
        if (row == null) {
            JOptionPane.showMessageDialog(this, "Pilih data agunan yang akan dihapus.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Hapus data agunan untuk pinjaman " + row.noPinjaman() + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            agunanDAO.delete(row.idAgunan());
            refreshSetelahSimpan();
            JOptionPane.showMessageDialog(this, "Data agunan berhasil dihapus.");
        } catch (SQLException ex) {
            tampilkanError("Tidak bisa menghapus data agunan.", ex);
        }
    }

    private AgunanDAO.AgunanRow getSelectedData() {
        int viewRow = jTable1.getSelectedRow();
        if (viewRow < 0) {
            return null;
        }

        int modelRow = jTable1.convertRowIndexToModel(viewRow);
        if (modelRow < 0 || modelRow >= dataAgunan.size()) {
            return null;
        }
        return dataAgunan.get(modelRow);
    }

    private void refreshSetelahSimpan() {
        try {
            muatFilter();
            muatData();
        } catch (SQLException ex) {
            tampilkanError("Tidak bisa memperbarui data agunan.", ex);
        }
    }

    private void pilihComboJikaAda(javax.swing.JComboBox<String> comboBox, Object value) {
        if (value == null) {
            return;
        }
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (value.toString().equals(comboBox.getItemAt(i))) {
                comboBox.setSelectedIndex(i);
                return;
            }
        }
    }

    private void exportCsv() {
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada data agunan untuk diexport.");
            return;
        }

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export Data Agunan");
        chooser.setFileFilter(new FileNameExtensionFilter("CSV File (*.csv)", "csv"));
        chooser.setSelectedFile(new File("data_agunan.csv"));
        if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        if (!file.getName().toLowerCase().endsWith(".csv")) {
            file = new File(file.getParentFile(), file.getName() + ".csv");
        }

        try (PrintWriter writer = new PrintWriter(new OutputStreamWriter(
                new FileOutputStream(file), StandardCharsets.UTF_8))) {
            writer.print('\ufeff');
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int col = 0; col < model.getColumnCount(); col++) {
                if (col > 0) {
                    writer.print(",");
                }
                writer.print(escapeCsv(model.getColumnName(col)));
            }
            writer.println();

            for (int row = 0; row < model.getRowCount(); row++) {
                for (int col = 0; col < model.getColumnCount(); col++) {
                    if (col > 0) {
                        writer.print(",");
                    }
                    Object value = model.getValueAt(row, col);
                    writer.print(escapeCsv(value == null ? "" : value.toString()));
                }
                writer.println();
            }
            JOptionPane.showMessageDialog(this, "Data agunan berhasil diexport.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal export data agunan.\n" + ex.getMessage());
        }
    }

    private String escapeCsv(String value) {
        String text = value == null ? "" : value;
        if (text.contains("\"") || text.contains(",") || text.contains("\n") || text.contains("\r")) {
            return "\"" + text.replace("\"", "\"\"") + "\"";
        }
        return text;
    }

    private String formatUang(BigDecimal value) {
        return PengaturanSistem.formatUang(value);
    }

    private void tampilkanError(String pesan, Exception ex) {
        JOptionPane.showMessageDialog(
                this,
                pesan + "\n" + ex.getMessage(),
                "Manajemen Agunan",
                JOptionPane.ERROR_MESSAGE
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenAgunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenAgunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenAgunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenAgunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenAgunan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtExport;
    private javax.swing.JButton BtHapus;
    private javax.swing.JButton btTambah;
    private javax.swing.JComboBox<String> cbFilterJenis;
    private javax.swing.JComboBox<String> cbFilterStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
