/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PinjamanDAO;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julfi
 */
public class ManajemenPinjaman extends javax.swing.JPanel {
    private final PinjamanDAO pinjamanDAO = new PinjamanDAO();
    private final List<String> pilihanAnggota = new ArrayList<>();
    private final Map<String, String> namaAnggotaByPilihan = new HashMap<>();
    private boolean sedangFilterAnggota = false;

    /**
     * Creates new form MANAJEMEN_PINJAMAN
     */
    public ManajemenPinjaman() {
        initComponents();
        tfNamaPinjaman.setEditable(false);
        tfBungaPinjaman.setEditable(false);
        cbAnggotaPinjaman.setEditable(true);
        muatComboAnggota();
        aktifkanSearchComboAnggota();
        aktifkanSearchPinjaman();
        resetFormPinjaman();
        kosongkanTabelPinjaman();
        addHierarchyListener(evt -> {
        if ((evt.getChangeFlags() & java.awt.event.HierarchyEvent.SHOWING_CHANGED) != 0
                && isShowing()) {
            muatComboAnggota();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarpinjaman = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TfSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblpinjamanaktif = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbAnggotaPinjaman = new javax.swing.JComboBox<>();
        tfNamaPinjaman = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfJumlahPinjaman = new javax.swing.JTextField();
        tfTenorPinjaman = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfBungaPinjaman = new javax.swing.JTextField();
        tfStatusPinjaman = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSimpanPinjaman = new javax.swing.JButton();
        btnResetPinjaman = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Daftar Pinjaman Anggota");

        tabelDaftarpinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Tanggal Pinjaman", "Jumlah", "Tenor", "Angsuran/Bln", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelDaftarpinjaman);
        if (tabelDaftarpinjaman.getColumnModel().getColumnCount() > 0) {
            tabelDaftarpinjaman.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Search :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Pinjaman Aktif :");

        lblpinjamanaktif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpinjamanaktif.setText("Rp. 0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpinjamanaktif, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblpinjamanaktif))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Input Pinjaman");

        jLabel1.setText("No. Anggota");

        cbAnggotaPinjaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Nama");

        jLabel3.setText("Jumlah Pinjaman");

        jLabel4.setText("Tenor (Bulan)");

        jLabel5.setText("Bungan (%)");

        tfStatusPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStatusPinjamanActionPerformed(evt);
            }
        });

        jLabel6.setText("Tujuan");

        btnSimpanPinjaman.setBackground(new java.awt.Color(0, 51, 204));
        btnSimpanPinjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpanPinjaman.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPinjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/diskette.png"))); // NOI18N
        btnSimpanPinjaman.setText("Simpan");
        btnSimpanPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPinjamanActionPerformed(evt);
            }
        });

        btnResetPinjaman.setBackground(new java.awt.Color(153, 0, 0));
        btnResetPinjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPinjaman.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPinjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/undowhite.png"))); // NOI18N
        btnResetPinjaman.setText("Reset");
        btnResetPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPinjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNamaPinjaman)
                            .addComponent(cbAnggotaPinjaman, 0, 145, Short.MAX_VALUE)
                            .addComponent(tfJumlahPinjaman)
                            .addComponent(tfTenorPinjaman)
                            .addComponent(tfBungaPinjaman)
                            .addComponent(tfStatusPinjaman))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnSimpanPinjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetPinjaman)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbAnggotaPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfJumlahPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTenorPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfBungaPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfStatusPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPinjaman)
                    .addComponent(btnResetPinjaman))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPinjamanActionPerformed
        simpanDataPinjaman();
    }//GEN-LAST:event_btnSimpanPinjamanActionPerformed

    private void btnResetPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPinjamanActionPerformed
        resetFormPinjaman();
    }//GEN-LAST:event_btnResetPinjamanActionPerformed

    private void tfStatusPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStatusPinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStatusPinjamanActionPerformed

    private void simpanDataPinjaman() {
        String noAnggota = getNoAnggotaTerpilih();
        BigDecimal jumlahPinjaman = parseNominal(tfJumlahPinjaman.getText());
        int tenor = parseInteger(tfTenorPinjaman.getText());
        BigDecimal bungaPersen = PengaturanSistem.muat().persenBunga();
        String tujuan = tfStatusPinjaman.getText().trim();

        if (noAnggota.isEmpty() || tfNamaPinjaman.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih No. Anggota terlebih dahulu.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jumlahPinjaman.compareTo(BigDecimal.ZERO) <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah pinjaman harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tenor <= 0) {
            JOptionPane.showMessageDialog(this, "Tenor pinjaman harus lebih dari 0 bulan.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (bungaPersen.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "Bunga tidak boleh kurang dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        BigDecimal totalBunga = jumlahPinjaman.multiply(bungaPersen).divide(new BigDecimal("100"), 2, RoundingMode.HALF_UP);
        BigDecimal totalPinjaman = jumlahPinjaman.add(totalBunga);
        BigDecimal angsuranPerBulan = totalPinjaman.divide(new BigDecimal(tenor), 2, RoundingMode.HALF_UP);

        try {
            pinjamanDAO.insert(noAnggota, jumlahPinjaman, tenor, bungaPersen, angsuranPerBulan, tujuan);
            JOptionPane.showMessageDialog(this, "Data pinjaman berhasil disimpan.\nAngsuran/Bulan: " + formatRupiah(angsuranPerBulan));
            resetFormPinjaman();
            loadDataPinjaman(TfSearch.getText().trim());
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menyimpan data pinjaman.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void muatComboAnggota() {
        pilihanAnggota.clear();
        namaAnggotaByPilihan.clear();

        try {
            for (PinjamanDAO.AnggotaPilihan anggota : pinjamanDAO.getAnggotaAktif()) {
                String pilihan = anggota.pilihan();

                pilihanAnggota.add(pilihan);
                namaAnggotaByPilihan.put(pilihan, anggota.nama());
            }

            isiModelComboAnggota(pilihanAnggota, "");
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data anggota.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void aktifkanSearchComboAnggota() {
        JTextField editor = (JTextField) cbAnggotaPinjaman.getEditor().getEditorComponent();

        cbAnggotaPinjaman.addActionListener(e -> isiNamaAnggotaTerpilih());
        editor.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterAnggota();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterAnggota();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterAnggota();
            }

            private void filterAnggota() {
                if (sedangFilterAnggota) {
                    return;
                }

                SwingUtilities.invokeLater(() -> {
                    String keyword = editor.getText();
                    List<String> hasil = new ArrayList<>();

                    for (String pilihan : pilihanAnggota) {
                        if (pilihan.toLowerCase().contains(keyword.toLowerCase())) {
                            hasil.add(pilihan);
                        }
                    }

                    isiModelComboAnggota(hasil, keyword);
                    if (!keyword.isBlank()) {
                        cbAnggotaPinjaman.showPopup();
                    }
                });
            }
        });
    }

    private void isiModelComboAnggota(List<String> data, String teksEditor) {
        sedangFilterAnggota = true;

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        cbAnggotaPinjaman.setModel(model);
        cbAnggotaPinjaman.setSelectedItem(teksEditor);

        sedangFilterAnggota = false;
    }

    private void isiNamaAnggotaTerpilih() {
        Object selectedItem = cbAnggotaPinjaman.getSelectedItem();
        if (selectedItem == null) {
            tfNamaPinjaman.setText("");
            kosongkanTabelPinjaman();
            return;
        }

        String pilihan = selectedItem.toString();
        if (pilihan.isBlank()) {
            tfNamaPinjaman.setText("");
            kosongkanTabelPinjaman();
            return;
        }

        tfNamaPinjaman.setText(namaAnggotaByPilihan.getOrDefault(pilihan, ""));
        if (tfNamaPinjaman.getText().trim().isEmpty()) {
            kosongkanTabelPinjaman();
            return;
        }

        loadDataPinjaman(TfSearch.getText().trim());
    }

    private String getNoAnggotaTerpilih() {
        Object selectedItem = cbAnggotaPinjaman.getSelectedItem();
        if (selectedItem == null) {
            return "";
        }

        String pilihan = selectedItem.toString().trim();
        int separatorIndex = pilihan.indexOf(" - ");
        if (separatorIndex > -1) {
            return pilihan.substring(0, separatorIndex).trim();
        }

        return pilihan;
    }

    private void loadDataPinjaman() {
        loadDataPinjaman("");
    }

    private void loadDataPinjaman(String keyword) {
        String noAnggotaFilter = getNoAnggotaTerpilih();
        if (noAnggotaFilter.isEmpty()) {
            kosongkanTabelPinjaman();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tabelDaftarpinjaman.getModel();
        model.setRowCount(0);

        BigDecimal totalAktif = BigDecimal.ZERO;

        try {
            int nomor = 1;
            for (PinjamanDAO.PinjamanRow row : pinjamanDAO.searchByAnggota(noAnggotaFilter, keyword)) {
                if ("Aktif".equalsIgnoreCase(row.status())) {
                    totalAktif = totalAktif.add(row.jumlah());
                }

                model.addRow(new Object[]{
                    nomor++,
                    row.nama(),
                    row.tanggalPinjaman(),
                    formatRupiah(row.jumlah()),
                    row.tenor(),
                    formatRupiah(row.angsuranPerBulan()),
                    row.status()
                });
            }

            lblpinjamanaktif.setText(formatRupiah(totalAktif));
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data pinjaman.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void kosongkanTabelPinjaman() {
        DefaultTableModel model = (DefaultTableModel) tabelDaftarpinjaman.getModel();
        model.setRowCount(0);
        lblpinjamanaktif.setText(formatRupiah(BigDecimal.ZERO));
    }

    private void aktifkanSearchPinjaman() {
        TfSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cariPinjaman();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                cariPinjaman();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                cariPinjaman();
            }

            private void cariPinjaman() {
                loadDataPinjaman(TfSearch.getText().trim());
            }
        });
    }

    private BigDecimal parseNominal(String value) {
        if (value == null || value.isBlank()) {
            return BigDecimal.ZERO;
        }

        String cleaned = value
                .replace("Rp", "")
                .replace("rp", "")
                .replace(".", "")
                .replace(",", ".")
                .trim();

        try {
            return new BigDecimal(cleaned);
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private int parseInteger(String value) {
        if (value == null || value.isBlank()) {
            return 0;
        }

        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException ex) {
            return 0;
        }
    }

    private String formatRupiah(BigDecimal value) {
        return PengaturanSistem.formatUang(value);
    }

    private void resetFormPinjaman() {
        cbAnggotaPinjaman.setSelectedItem("");
        tfNamaPinjaman.setText("");
        tfJumlahPinjaman.setText("");
        tfTenorPinjaman.setText("");
        tfBungaPinjaman.setText(PengaturanSistem.muat().persenBunga().stripTrailingZeros().toPlainString());
        tfStatusPinjaman.setText("");
        kosongkanTabelPinjaman();
        cbAnggotaPinjaman.requestFocus();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfSearch;
    private javax.swing.JButton btnResetPinjaman;
    private javax.swing.JButton btnSimpanPinjaman;
    private javax.swing.JComboBox<String> cbAnggotaPinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpinjamanaktif;
    private javax.swing.JTable tabelDaftarpinjaman;
    private javax.swing.JTextField tfBungaPinjaman;
    private javax.swing.JTextField tfJumlahPinjaman;
    private javax.swing.JTextField tfNamaPinjaman;
    private javax.swing.JTextField tfStatusPinjaman;
    private javax.swing.JTextField tfTenorPinjaman;
    // End of variables declaration//GEN-END:variables
}
