/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.TransaksiDAO;
import java.beans.PropertyChangeEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rangga
 */
public class Transaksi extends javax.swing.JPanel {
    private final TransaksiDAO transaksiDAO = new TransaksiDAO();

    /**
     * Creates new form tampilan_baru
     */
    public Transaksi() {
        initComponents();
        cbJenTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "- Semua -", "Pinjaman", "Simpanan", "Angsuran"
        }));
        aktifkanFilterRealtime();
        loadDataTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbJenTransaksi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jdTanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Jenis Transaksi");

        cbJenTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Semua -", "Pinjaman", "Simpanan" }));
        cbJenTransaksi.addActionListener(this::cbJenTransaksiActionPerformed);

        jLabel2.setText("Tanggal :");

        jLabel3.setText("Search :");

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Jenis Transaksi", "No. Anggota", "Anggota", "Debet", "Kredit", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabeltransaksi);
        if (tabeltransaksi.getColumnModel().getColumnCount() > 0) {
            tabeltransaksi.getColumnModel().getColumn(0).setResizable(false);
            tabeltransaksi.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        jLabel4.setText("Total Debet :");

        jLabel5.setText("Total Kredit :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbJenTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(25, 25, 25)
                            .addComponent(jdTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(424, 424, 424)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(107, 107, 107)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jdTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbJenTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGap(115, 115, 115)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbJenTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenTransaksiActionPerformed
        loadDataTransaksi();
    }//GEN-LAST:event_cbJenTransaksiActionPerformed

    private void loadDataTransaksi() {
        DefaultTableModel model = (DefaultTableModel) tabeltransaksi.getModel();
        model.setRowCount(0);

        try {
            String jenis = cbJenTransaksi.getSelectedItem() == null ? "- Semua -" : cbJenTransaksi.getSelectedItem().toString();
            java.sql.Date tanggal = jdTanggal.getDate() == null ? null : new java.sql.Date(jdTanggal.getDate().getTime());
            String search = tfSearch.getText().trim();

            TransaksiDAO.HasilTransaksi hasil = transaksiDAO.search(jenis, tanggal, search);
            int nomor = 1;
            for (TransaksiDAO.TransaksiRow row : hasil.rows()) {
                model.addRow(new Object[]{
                    nomor++,
                    row.tanggal(),
                    row.jenisTransaksi(),
                    row.noAnggota(),
                    row.nama(),
                    formatRupiah(row.debet()),
                    formatRupiah(row.kredit()),
                    row.keterangan()
                });
            }

            jLabel4.setText("Total Debet : " + formatRupiah(hasil.totalDebet()));
            jLabel5.setText("Total Kredit : " + formatRupiah(hasil.totalKredit()));
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data transaksi.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void aktifkanFilterRealtime() {
        tfSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                loadDataTransaksi();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                loadDataTransaksi();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                loadDataTransaksi();
            }
        });

        jdTanggal.addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if ("date".equals(evt.getPropertyName())) {
                loadDataTransaksi();
            }
        });
    }

    private String formatRupiah(BigDecimal value) {
        BigDecimal angka = value == null ? BigDecimal.ZERO : value;
        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        format.setMaximumFractionDigits(0);
        return format.format(angka);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJenTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdTanggal;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
