/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import Koneksi.Koneksi;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author feryo
 */
public class Angsuran extends javax.swing.JPanel {
    private final List<String> pilihanPinjaman = new ArrayList<>();
    private final Map<String, Integer> idPinjamanByPilihan = new HashMap<>();
    private final Map<String, String> namaAnggotaByPilihan = new HashMap<>();
    private boolean sedangFilterPinjaman = false;

    /**
     * Creates new form Angsuran
     */
    public Angsuran() {
        initComponents();
        tnamaang.setEditable(false);
        jTextField5.setEditable(false);
        cbbnopinjaman.setEditable(true);
        muatComboPinjaman();
        aktifkanSearchComboPinjaman();
        btnresetang.addActionListener(e -> resetFormAngsuran());
        resetFormAngsuran();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbnopinjaman = new javax.swing.JComboBox<>();
        tnamaang = new javax.swing.JTextField();
        tang = new javax.swing.JTextField();
        tjmlang = new javax.swing.JTextField();
        tketang = new javax.swing.JTextField();
        btnsimpanang = new javax.swing.JButton();
        btnresetang = new javax.swing.JButton();
        tglangs = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelangsuran = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("INPUT ANGSURAN");

        jLabel2.setText("No. Pinjaman ");

        jLabel3.setText("Nama ");

        jLabel4.setText("Jumlah Bayar");

        jLabel5.setText("Angsuran ke ");

        jLabel6.setText("Tanggal Bayar ");

        jLabel7.setText("Keterangan");

        cbbnopinjaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tnamaang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaangActionPerformed(evt);
            }
        });

        tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangActionPerformed(evt);
            }
        });

        tjmlang.setText("Rp .");

        tketang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tketangActionPerformed(evt);
            }
        });

        btnsimpanang.setBackground(new java.awt.Color(51, 153, 255));
        btnsimpanang.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpanang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Icon/diskette.png"))); // NOI18N
        btnsimpanang.setText("Simpan");
        btnsimpanang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanangActionPerformed(evt);
            }
        });

        btnresetang.setBackground(new java.awt.Color(255, 0, 51));
        btnresetang.setForeground(new java.awt.Color(255, 255, 255));
        btnresetang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Icon/undowhite.png"))); // NOI18N
        btnresetang.setText("Reset");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tglangs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tjmlang)
                                    .addComponent(cbbnopinjaman, 0, 125, Short.MAX_VALUE)
                                    .addComponent(tnamaang)
                                    .addComponent(tang)
                                    .addComponent(tketang)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsimpanang)
                                .addGap(33, 33, 33)
                                .addComponent(btnresetang, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbnopinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnamaang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglangs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tjmlang))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tketang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpanang)
                    .addComponent(btnresetang))
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("RIWAYAT ANGSURAN");

        tabelangsuran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabelangsuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Angsuran Ke", "Tgl Jatuh Tempo", "Jumlah ", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelangsuran);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField5.setText("SISA PINJAMAN");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tnamaangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaangActionPerformed

    private void tketangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tketangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tketangActionPerformed

    private void btnsimpanangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanangActionPerformed
        simpanDataAngsuran();
    }//GEN-LAST:event_btnsimpanangActionPerformed

    private void tangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tangActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void simpanDataAngsuran() {
        Integer idPinjaman = getIdPinjamanTerpilih();
        int angsuranKe = parseInteger(tang.getText());
        BigDecimal jumlahBayar = parseNominal(tjmlang.getText());
        Date tanggalBayar = tglangs.getDate();

        if (idPinjaman == null) {
            JOptionPane.showMessageDialog(this, "Pilih No. Pinjaman terlebih dahulu.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (angsuranKe <= 0) {
            JOptionPane.showMessageDialog(this, "Angsuran ke harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tanggalBayar == null) {
            JOptionPane.showMessageDialog(this, "Tanggal bayar wajib diisi.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jumlahBayar.compareTo(BigDecimal.ZERO) <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah bayar harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection connection = Koneksi.getConnection()) {
            connection.setAutoCommit(false);

            try {
                PinjamanInfo pinjaman = getPinjamanInfo(connection, idPinjaman);
                BigDecimal sisaSebelumBayar = pinjaman.jumlahPinjaman.subtract(pinjaman.totalDibayar);

                if (sisaSebelumBayar.compareTo(BigDecimal.ZERO) <= 0) {
                    JOptionPane.showMessageDialog(this, "Pinjaman ini sudah lunas.", "Validasi", JOptionPane.WARNING_MESSAGE);
                    connection.rollback();
                    return;
                }

                if (jumlahBayar.compareTo(sisaSebelumBayar) > 0) {
                    int pilihan = JOptionPane.showConfirmDialog(
                            this,
                            "Jumlah bayar melebihi sisa pinjaman.\nSisa pinjaman: " + formatRupiah(sisaSebelumBayar) + "\nTetap simpan?",
                            "Konfirmasi",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );

                    if (pilihan != JOptionPane.YES_OPTION) {
                        connection.rollback();
                        return;
                    }
                }

                int idAngsuran = insertAngsuran(connection, idPinjaman, angsuranKe, tanggalBayar, jumlahBayar);
                insertTransaksiAngsuran(connection, pinjaman.idAnggota, idAngsuran, jumlahBayar);

                BigDecimal sisaSetelahBayar = sisaSebelumBayar.subtract(jumlahBayar);
                if (sisaSetelahBayar.compareTo(BigDecimal.ZERO) <= 0) {
                    updateStatusPinjaman(connection, idPinjaman, "Lunas");
                }

                connection.commit();
                JOptionPane.showMessageDialog(this, "Data angsuran berhasil disimpan.");
                muatComboPinjaman();
                resetFormAngsuran();
            } catch (SQLException | RuntimeException ex) {
                connection.rollback();
                throw ex;
            } finally {
                connection.setAutoCommit(true);
            }
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menyimpan data angsuran.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void muatComboPinjaman() {
        pilihanPinjaman.clear();
        idPinjamanByPilihan.clear();
        namaAnggotaByPilihan.clear();

        String sql = """
                SELECT p.id_pinjaman, p.no_pinjaman, a.no_anggota, a.nama
                FROM pinjaman p
                JOIN anggota a ON a.id_anggota = p.id_anggota
                WHERE p.status = 'Aktif'
                ORDER BY p.id_pinjaman ASC
                """;

        try (Connection connection = Koneksi.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet result = statement.executeQuery()) {

            while (result.next()) {
                String pilihan = result.getString("no_pinjaman") + " - "
                        + result.getString("no_anggota") + " - "
                        + result.getString("nama");

                pilihanPinjaman.add(pilihan);
                idPinjamanByPilihan.put(pilihan, result.getInt("id_pinjaman"));
                namaAnggotaByPilihan.put(pilihan, result.getString("nama"));
            }

            isiModelComboPinjaman(pilihanPinjaman, "");
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat data pinjaman.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void aktifkanSearchComboPinjaman() {
        JTextField editor = (JTextField) cbbnopinjaman.getEditor().getEditorComponent();

        cbbnopinjaman.addActionListener(e -> tampilkanPinjamanTerpilih());
        editor.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterPinjaman();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterPinjaman();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterPinjaman();
            }

            private void filterPinjaman() {
                if (sedangFilterPinjaman) {
                    return;
                }

                SwingUtilities.invokeLater(() -> {
                    String keyword = editor.getText();
                    List<String> hasil = new ArrayList<>();

                    for (String pilihan : pilihanPinjaman) {
                        if (pilihan.toLowerCase().contains(keyword.toLowerCase())) {
                            hasil.add(pilihan);
                        }
                    }

                    isiModelComboPinjaman(hasil, keyword);
                    if (!keyword.isBlank()) {
                        cbbnopinjaman.showPopup();
                    }
                });
            }
        });
    }

    private void isiModelComboPinjaman(List<String> data, String teksEditor) {
        sedangFilterPinjaman = true;

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        cbbnopinjaman.setModel(model);
        cbbnopinjaman.setSelectedItem(teksEditor);

        sedangFilterPinjaman = false;
    }

    private void tampilkanPinjamanTerpilih() {
        Integer idPinjaman = getIdPinjamanTerpilih();
        Object selectedItem = cbbnopinjaman.getSelectedItem();

        if (idPinjaman == null || selectedItem == null) {
            tnamaang.setText("");
            jTextField5.setText("SISA PINJAMAN");
            kosongkanTabelAngsuran();
            return;
        }

        String pilihan = selectedItem.toString();
        tnamaang.setText(namaAnggotaByPilihan.getOrDefault(pilihan, ""));

        try (Connection connection = Koneksi.getConnection()) {
            PinjamanInfo info = getPinjamanInfo(connection, idPinjaman);
            BigDecimal sisa = info.jumlahPinjaman.subtract(info.totalDibayar);
            jTextField5.setText("SISA PINJAMAN: " + formatRupiah(sisa));
            tang.setText(String.valueOf(getAngsuranBerikutnya(connection, idPinjaman)));
            tjmlang.setText(formatAngkaPlain(info.angsuranPerBulan));
            loadRiwayatAngsuran(connection, idPinjaman);
        } catch (SQLException | RuntimeException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat detail pinjaman.\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private Integer getIdPinjamanTerpilih() {
        Object selectedItem = cbbnopinjaman.getSelectedItem();
        if (selectedItem == null) {
            return null;
        }

        return idPinjamanByPilihan.get(selectedItem.toString());
    }

    private PinjamanInfo getPinjamanInfo(Connection connection, int idPinjaman) throws SQLException {
        String sql = """
                SELECT p.id_anggota, p.jumlah_pinjaman, p.angsuran_per_bulan,
                       COALESCE(SUM(a.jumlah_bayar), 0) AS total_dibayar
                FROM pinjaman p
                LEFT JOIN angsuran a ON a.id_pinjaman = p.id_pinjaman
                WHERE p.id_pinjaman = ?
                GROUP BY p.id_pinjaman, p.id_anggota, p.jumlah_pinjaman, p.angsuran_per_bulan
                """;

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, idPinjaman);

            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    return new PinjamanInfo(
                            result.getInt("id_anggota"),
                            result.getBigDecimal("jumlah_pinjaman"),
                            result.getBigDecimal("angsuran_per_bulan"),
                            result.getBigDecimal("total_dibayar")
                    );
                }
            }
        }

        throw new SQLException("Data pinjaman tidak ditemukan.");
    }

    private int getAngsuranBerikutnya(Connection connection, int idPinjaman) throws SQLException {
        String sql = "SELECT COALESCE(MAX(angsuran_ke), 0) + 1 AS berikutnya FROM angsuran WHERE id_pinjaman = ?";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, idPinjaman);

            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    return result.getInt("berikutnya");
                }
            }
        }

        return 1;
    }

    private int insertAngsuran(Connection connection, int idPinjaman, int angsuranKe,
            Date tanggalBayar, BigDecimal jumlahBayar) throws SQLException {
        String sql = """
                INSERT INTO angsuran (
                  id_pinjaman, angsuran_ke, tanggal_jatuh_tempo, tanggal_bayar,
                  jumlah_bayar, status, keterangan
                ) VALUES (?, ?, NULL, ?, ?, 'Dibayar', ?)
                """;

        try (PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            statement.setInt(1, idPinjaman);
            statement.setInt(2, angsuranKe);
            statement.setDate(3, new java.sql.Date(tanggalBayar.getTime()));
            statement.setBigDecimal(4, jumlahBayar);
            statement.setString(5, tketang.getText().trim());
            statement.executeUpdate();

            try (ResultSet keys = statement.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
            }
        }

        throw new SQLException("ID angsuran gagal dibuat.");
    }

    private void insertTransaksiAngsuran(Connection connection, int idAnggota, int idAngsuran,
            BigDecimal jumlahBayar) throws SQLException {
        String sql = """
                INSERT INTO transaksi (
                  jenis_transaksi, id_anggota, referensi_tabel, referensi_id, debet, kredit, keterangan
                ) VALUES ('Angsuran', ?, 'angsuran', ?, ?, 0, ?)
                """;

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, idAnggota);
            statement.setInt(2, idAngsuran);
            statement.setBigDecimal(3, jumlahBayar);
            statement.setString(4, tketang.getText().trim());
            statement.executeUpdate();
        }
    }

    private void updateStatusPinjaman(Connection connection, int idPinjaman, String status) throws SQLException {
        String sql = "UPDATE pinjaman SET status = ? WHERE id_pinjaman = ?";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, status);
            statement.setInt(2, idPinjaman);
            statement.executeUpdate();
        }
    }

    private void loadRiwayatAngsuran(Connection connection, int idPinjaman) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tabelangsuran.getModel();
        model.setRowCount(0);

        String sql = """
                SELECT angsuran_ke, tanggal_bayar, jumlah_bayar, status, keterangan
                FROM angsuran
                WHERE id_pinjaman = ?
                ORDER BY angsuran_ke ASC
                """;

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, idPinjaman);

            try (ResultSet result = statement.executeQuery()) {
                int nomor = 1;
                while (result.next()) {
                    model.addRow(new Object[]{
                        nomor++,
                        result.getInt("angsuran_ke"),
                        result.getDate("tanggal_bayar"),
                        formatRupiah(result.getBigDecimal("jumlah_bayar")),
                        result.getString("status")
                    });
                }
            }
        }
    }

    private void kosongkanTabelAngsuran() {
        DefaultTableModel model = (DefaultTableModel) tabelangsuran.getModel();
        model.setRowCount(0);
    }

    private BigDecimal parseNominal(String value) {
        if (value == null || value.isBlank()) {
            return BigDecimal.ZERO;
        }

        String cleaned = value
                .replace("Rp", "")
                .replace("rp", "")
                .replace(".", "")
                .replace(",", ".")
                .trim();

        try {
            return new BigDecimal(cleaned);
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private int parseInteger(String value) {
        if (value == null || value.isBlank()) {
            return 0;
        }

        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException ex) {
            return 0;
        }
    }

    private String formatRupiah(BigDecimal value) {
        BigDecimal angka = value == null ? BigDecimal.ZERO : value;
        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        format.setMaximumFractionDigits(0);
        return format.format(angka);
    }

    private String formatAngkaPlain(BigDecimal value) {
        BigDecimal angka = value == null ? BigDecimal.ZERO : value;
        return angka.stripTrailingZeros().toPlainString();
    }

    private void resetFormAngsuran() {
        cbbnopinjaman.setSelectedItem("");
        tnamaang.setText("");
        tang.setText("");
        tglangs.setDate(new Date());
        tjmlang.setText("");
        tketang.setText("");
        jTextField5.setText("SISA PINJAMAN");
        kosongkanTabelAngsuran();
        cbbnopinjaman.requestFocus();
    }

    private static class PinjamanInfo {
        private final int idAnggota;
        private final BigDecimal jumlahPinjaman;
        private final BigDecimal angsuranPerBulan;
        private final BigDecimal totalDibayar;

        private PinjamanInfo(int idAnggota, BigDecimal jumlahPinjaman,
                BigDecimal angsuranPerBulan, BigDecimal totalDibayar) {
            this.idAnggota = idAnggota;
            this.jumlahPinjaman = jumlahPinjaman == null ? BigDecimal.ZERO : jumlahPinjaman;
            this.angsuranPerBulan = angsuranPerBulan == null ? BigDecimal.ZERO : angsuranPerBulan;
            this.totalDibayar = totalDibayar == null ? BigDecimal.ZERO : totalDibayar;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Angsuran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnresetang;
    private javax.swing.JButton btnsimpanang;
    private javax.swing.JComboBox<String> cbbnopinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tabelangsuran;
    private javax.swing.JTextField tang;
    private com.toedter.calendar.JDateChooser tglangs;
    private javax.swing.JTextField tjmlang;
    private javax.swing.JTextField tketang;
    private javax.swing.JTextField tnamaang;
    // End of variables declaration//GEN-END:variables
}
