/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;
import java.awt.CardLayout;
/**
 *
 * @author BeniAkbar
 */
public class Menu extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        // Add action listeners here so NetBeans doesn't overwrite them
        bsimpanan1.addActionListener(this::bsimpanan1ActionPerformed);
        bangsuran.addActionListener(this::bangsuranActionPerformed);
        blaporan.addActionListener(this::blaporanActionPerformed);
        bpengaturan.addActionListener(this::bpengaturanActionPerformed);
        blogout.addActionListener(this::blogoutActionPerformed);

        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));
        panelMenu.removeAll();
        java.awt.Component[] buttons = {bdashboard, banggota, bsimpanan1, bsimpanan, bangsuran, btransaksi, blaporan, bpengaturan, blogout};
        for (java.awt.Component btn : buttons) {
            javax.swing.JButton b = (javax.swing.JButton) btn;
            b.setMaximumSize(new java.awt.Dimension(Short.MAX_VALUE, 30));
            panelMenu.add(javax.swing.Box.createVerticalStrut(10));
            panelMenu.add(b);
        }

        // Override the NetBeans layout entirely for the main JFrame to fix the gap issue!
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);
        getContentPane().add(panelMenu, java.awt.BorderLayout.WEST);
        
        panelContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        DashboardPanel dashboard = new DashboardPanel();

        panelContent.add(dashboard, java.awt.BorderLayout.CENTER);

        panelContent.revalidate();

        panelContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        bdashboard = new javax.swing.JButton();
        banggota = new javax.swing.JButton();
        bsimpanan = new javax.swing.JButton();
        bsimpanan1 = new javax.swing.JButton();
        bangsuran = new javax.swing.JButton();
        btransaksi = new javax.swing.JButton();
        blaporan = new javax.swing.JButton();
        bpengaturan = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bdashboard.setText("🏠 Dashboard");
        bdashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdashboard.setPreferredSize(new java.awt.Dimension(104, 23));
        bdashboard.addActionListener(this::bdashboardActionPerformed);

        banggota.setText("👥 Manajemen Anggota ");
        banggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        banggota.addActionListener(this::banggotaActionPerformed);

        bsimpanan.setText("🏛️ Manajemen Pinjaman");
        bsimpanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsimpanan.addActionListener(this::bsimpananActionPerformed);

        bsimpanan1.setText("🏛️ Manajemen Simpanan");
        bsimpanan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        bangsuran.setText("💰 Angsuran");
        bangsuran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btransaksi.setText("💲 Transaksi");
        btransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btransaksi.addActionListener(this::btransaksiActionPerformed);

        blaporan.setText("📊 Laporan");
        blaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        bpengaturan.setText("🛠️ Pengaturan");
        bpengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        blogout.setText("⏻ Logout");
        blogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsimpanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bangsuran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bpengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsimpanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1.setBackground(java.awt.Color.blue);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KOPERASI RAYA ABADI SAUDARA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdashboardActionPerformed
    panelContent.removeAll();

    DashboardPanel dashboard = new DashboardPanel();

    panelContent.add(dashboard, java.awt.BorderLayout.CENTER);

    panelContent.revalidate();

    panelContent.repaint();
 // TODO add your handling code here:
    }//GEN-LAST:event_bdashboardActionPerformed

    private void banggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banggotaActionPerformed
        // TODO add your handling code here:
        panelContent.removeAll();

    manajemen_anggotaa anggota = new manajemen_anggotaa();

    panelContent.add(anggota, java.awt.BorderLayout.CENTER);

    panelContent.revalidate();

    panelContent.repaint();
    }//GEN-LAST:event_banggotaActionPerformed

    private void btransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransaksiActionPerformed

   panelContent.removeAll();

    tampilan_baru panel = new tampilan_baru();

    panelContent.add(panel, java.awt.BorderLayout.CENTER);

    panelContent.revalidate();

    panelContent.repaint();
    }//GEN-LAST:event_btransaksiActionPerformed

    private void bsimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpananActionPerformed
        try {
            panelContent.removeAll();
            MANAJEMEN_PINJAMAN panel = new MANAJEMEN_PINJAMAN();
            panelContent.add(panel, java.awt.BorderLayout.CENTER);
            panelContent.revalidate();
            panelContent.repaint();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat halaman: " + e.getMessage() + "\n\nTolong lakukan CLEAN AND BUILD (logo palu dan sapu) di NetBeans!");
            e.printStackTrace();
        } catch (Error err) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error sistem: " + err.getMessage() + "\n\nTolong lakukan CLEAN AND BUILD (logo palu dan sapu) di NetBeans!");
            err.printStackTrace();
        }
    }//GEN-LAST:event_bsimpananActionPerformed

    private void bsimpanan1ActionPerformed(java.awt.event.ActionEvent evt) {
        panelContent.removeAll();
        manajemen_simpanan panel = new manajemen_simpanan();
        panelContent.add(panel, java.awt.BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }

    private void bangsuranActionPerformed(java.awt.event.ActionEvent evt) {
        panelContent.removeAll();
        Angsuran panel = new Angsuran();
        panelContent.add(panel, java.awt.BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }

    private void blaporanActionPerformed(java.awt.event.ActionEvent evt) {
        panelContent.removeAll();
        Laporan panel = new Laporan();
        panelContent.add(panel, java.awt.BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }

    private void bpengaturanActionPerformed(java.awt.event.ActionEvent evt) {
        panelContent.removeAll();
        Pengaturan panel = new Pengaturan();
        panelContent.add(panel, java.awt.BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        new Login().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton banggota;
    private javax.swing.JButton bangsuran;
    private javax.swing.JButton bdashboard;
    private javax.swing.JButton blaporan;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bpengaturan;
    private javax.swing.JButton bsimpanan;
    private javax.swing.JButton bsimpanan1;
    private javax.swing.JButton btransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

}